// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: treasury.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreateMultisig creates a multisig wallet.
type MsgCreateMultisig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// creator is the address creating the multisig (bech32)
	Creator       string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Members       []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Threshold     uint32   `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Balance       uint64   `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateMultisig) Reset() {
	*x = MsgCreateMultisig{}
	mi := &file_treasury_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateMultisig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateMultisig) ProtoMessage() {}

func (x *MsgCreateMultisig) ProtoReflect() protoreflect.Message {
	mi := &file_treasury_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateMultisig.ProtoReflect.Descriptor instead.
func (*MsgCreateMultisig) Descriptor() ([]byte, []int) {
	return file_treasury_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateMultisig) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *MsgCreateMultisig) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreateMultisig) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MsgCreateMultisig) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *MsgCreateMultisig) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type MsgCreateMultisigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateMultisigResponse) Reset() {
	*x = MsgCreateMultisigResponse{}
	mi := &file_treasury_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateMultisigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateMultisigResponse) ProtoMessage() {}

func (x *MsgCreateMultisigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_treasury_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateMultisigResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateMultisigResponse) Descriptor() ([]byte, []int) {
	return file_treasury_proto_rawDescGZIP(), []int{1}
}

// MsgScheduleDisbursement schedules a disbursement from a multisig.
type MsgScheduleDisbursement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ReleaseAtUnix int64                  `protobuf:"varint,5,opt,name=release_at_unix,json=releaseAtUnix,proto3" json:"release_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgScheduleDisbursement) Reset() {
	*x = MsgScheduleDisbursement{}
	mi := &file_treasury_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgScheduleDisbursement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgScheduleDisbursement) ProtoMessage() {}

func (x *MsgScheduleDisbursement) ProtoReflect() protoreflect.Message {
	mi := &file_treasury_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgScheduleDisbursement.ProtoReflect.Descriptor instead.
func (*MsgScheduleDisbursement) Descriptor() ([]byte, []int) {
	return file_treasury_proto_rawDescGZIP(), []int{2}
}

func (x *MsgScheduleDisbursement) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *MsgScheduleDisbursement) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MsgScheduleDisbursement) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MsgScheduleDisbursement) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MsgScheduleDisbursement) GetReleaseAtUnix() int64 {
	if x != nil {
		return x.ReleaseAtUnix
	}
	return 0
}

type MsgScheduleDisbursementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgScheduleDisbursementResponse) Reset() {
	*x = MsgScheduleDisbursementResponse{}
	mi := &file_treasury_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgScheduleDisbursementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgScheduleDisbursementResponse) ProtoMessage() {}

func (x *MsgScheduleDisbursementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_treasury_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgScheduleDisbursementResponse.ProtoReflect.Descriptor instead.
func (*MsgScheduleDisbursementResponse) Descriptor() ([]byte, []int) {
	return file_treasury_proto_rawDescGZIP(), []int{3}
}

// MsgApproveDisbursement records an approval from a multisig member.
type MsgApproveDisbursement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Approver      string                 `protobuf:"bytes,2,opt,name=approver,proto3" json:"approver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgApproveDisbursement) Reset() {
	*x = MsgApproveDisbursement{}
	mi := &file_treasury_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgApproveDisbursement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgApproveDisbursement) ProtoMessage() {}

func (x *MsgApproveDisbursement) ProtoReflect() protoreflect.Message {
	mi := &file_treasury_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgApproveDisbursement.ProtoReflect.Descriptor instead.
func (*MsgApproveDisbursement) Descriptor() ([]byte, []int) {
	return file_treasury_proto_rawDescGZIP(), []int{4}
}

func (x *MsgApproveDisbursement) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *MsgApproveDisbursement) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

type MsgApproveDisbursementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgApproveDisbursementResponse) Reset() {
	*x = MsgApproveDisbursementResponse{}
	mi := &file_treasury_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgApproveDisbursementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgApproveDisbursementResponse) ProtoMessage() {}

func (x *MsgApproveDisbursementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_treasury_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgApproveDisbursementResponse.ProtoReflect.Descriptor instead.
func (*MsgApproveDisbursementResponse) Descriptor() ([]byte, []int) {
	return file_treasury_proto_rawDescGZIP(), []int{5}
}

var File_treasury_proto protoreflect.FileDescriptor

const file_treasury_proto_rawDesc = "" +
	"\n" +
	"\x0etreasury.proto\x12\x18tmp.marketplace.treasury\"\x95\x01\n" +
	"\x11MsgCreateMultisig\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x18\n" +
	"\acreator\x18\x05 \x01(\tR\acreator\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\rR\tthreshold\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x04R\abalance\"\x1b\n" +
	"\x19MsgCreateMultisigResponse\"\x93\x01\n" +
	"\x17MsgScheduleDisbursement\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12&\n" +
	"\x0frelease_at_unix\x18\x05 \x01(\x03R\rreleaseAtUnix\"!\n" +
	"\x1fMsgScheduleDisbursementResponse\"J\n" +
	"\x16MsgApproveDisbursement\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x1a\n" +
	"\bapprover\x18\x02 \x01(\tR\bapprover\" \n" +
	"\x1eMsgApproveDisbursementResponse2\x84\x03\n" +
	"\x03Msg\x12r\n" +
	"\x0eCreateMultisig\x12+.tmp.marketplace.treasury.MsgCreateMultisig\x1a3.tmp.marketplace.treasury.MsgCreateMultisigResponse\x12\x84\x01\n" +
	"\x14ScheduleDisbursement\x121.tmp.marketplace.treasury.MsgScheduleDisbursement\x1a9.tmp.marketplace.treasury.MsgScheduleDisbursementResponse\x12\x81\x01\n" +
	"\x13ApproveDisbursement\x120.tmp.marketplace.treasury.MsgApproveDisbursement\x1a8.tmp.marketplace.treasury.MsgApproveDisbursementResponseB3Z1github.com/tmp/marketplace/x/treasury/types;typesb\x06proto3"

var (
	file_treasury_proto_rawDescOnce sync.Once
	file_treasury_proto_rawDescData []byte
)

func file_treasury_proto_rawDescGZIP() []byte {
	file_treasury_proto_rawDescOnce.Do(func() {
		file_treasury_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_treasury_proto_rawDesc), len(file_treasury_proto_rawDesc)))
	})
	return file_treasury_proto_rawDescData
}

var file_treasury_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_treasury_proto_goTypes = []any{
	(*MsgCreateMultisig)(nil),               // 0: tmp.marketplace.treasury.MsgCreateMultisig
	(*MsgCreateMultisigResponse)(nil),       // 1: tmp.marketplace.treasury.MsgCreateMultisigResponse
	(*MsgScheduleDisbursement)(nil),         // 2: tmp.marketplace.treasury.MsgScheduleDisbursement
	(*MsgScheduleDisbursementResponse)(nil), // 3: tmp.marketplace.treasury.MsgScheduleDisbursementResponse
	(*MsgApproveDisbursement)(nil),          // 4: tmp.marketplace.treasury.MsgApproveDisbursement
	(*MsgApproveDisbursementResponse)(nil),  // 5: tmp.marketplace.treasury.MsgApproveDisbursementResponse
}
var file_treasury_proto_depIdxs = []int32{
	0, // 0: tmp.marketplace.treasury.Msg.CreateMultisig:input_type -> tmp.marketplace.treasury.MsgCreateMultisig
	2, // 1: tmp.marketplace.treasury.Msg.ScheduleDisbursement:input_type -> tmp.marketplace.treasury.MsgScheduleDisbursement
	4, // 2: tmp.marketplace.treasury.Msg.ApproveDisbursement:input_type -> tmp.marketplace.treasury.MsgApproveDisbursement
	1, // 3: tmp.marketplace.treasury.Msg.CreateMultisig:output_type -> tmp.marketplace.treasury.MsgCreateMultisigResponse
	3, // 4: tmp.marketplace.treasury.Msg.ScheduleDisbursement:output_type -> tmp.marketplace.treasury.MsgScheduleDisbursementResponse
	5, // 5: tmp.marketplace.treasury.Msg.ApproveDisbursement:output_type -> tmp.marketplace.treasury.MsgApproveDisbursementResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_treasury_proto_init() }
func file_treasury_proto_init() {
	if File_treasury_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_treasury_proto_rawDesc), len(file_treasury_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_treasury_proto_goTypes,
		DependencyIndexes: file_treasury_proto_depIdxs,
		MessageInfos:      file_treasury_proto_msgTypes,
	}.Build()
	File_treasury_proto = out.File
	file_treasury_proto_goTypes = nil
	file_treasury_proto_depIdxs = nil
}
