// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: marketplace/vault/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_SetupVault_FullMethodName    = "/marketplace.vault.v1.Msg/SetupVault"
	Msg_ConfirmVault_FullMethodName  = "/marketplace.vault.v1.Msg/ConfirmVault"
	Msg_UnlockAndSign_FullMethodName = "/marketplace.vault.v1.Msg/UnlockAndSign"
	Msg_DisableVault_FullMethodName  = "/marketplace.vault.v1.Msg/DisableVault"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg service for vault operations. NOTE: some fields are sensitive; ensure
// operators understand privacy implications before exposing these txs on-chain.
type MsgClient interface {
	SetupVault(ctx context.Context, in *MsgSetupVault, opts ...grpc.CallOption) (*MsgSetupVaultResponse, error)
	ConfirmVault(ctx context.Context, in *MsgConfirmVault, opts ...grpc.CallOption) (*MsgConfirmVaultResponse, error)
	UnlockAndSign(ctx context.Context, in *MsgUnlockAndSign, opts ...grpc.CallOption) (*MsgUnlockAndSignResponse, error)
	DisableVault(ctx context.Context, in *MsgDisableVault, opts ...grpc.CallOption) (*MsgDisableVaultResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetupVault(ctx context.Context, in *MsgSetupVault, opts ...grpc.CallOption) (*MsgSetupVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSetupVaultResponse)
	err := c.cc.Invoke(ctx, Msg_SetupVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConfirmVault(ctx context.Context, in *MsgConfirmVault, opts ...grpc.CallOption) (*MsgConfirmVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgConfirmVaultResponse)
	err := c.cc.Invoke(ctx, Msg_ConfirmVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnlockAndSign(ctx context.Context, in *MsgUnlockAndSign, opts ...grpc.CallOption) (*MsgUnlockAndSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUnlockAndSignResponse)
	err := c.cc.Invoke(ctx, Msg_UnlockAndSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DisableVault(ctx context.Context, in *MsgDisableVault, opts ...grpc.CallOption) (*MsgDisableVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDisableVaultResponse)
	err := c.cc.Invoke(ctx, Msg_DisableVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg service for vault operations. NOTE: some fields are sensitive; ensure
// operators understand privacy implications before exposing these txs on-chain.
type MsgServer interface {
	SetupVault(context.Context, *MsgSetupVault) (*MsgSetupVaultResponse, error)
	ConfirmVault(context.Context, *MsgConfirmVault) (*MsgConfirmVaultResponse, error)
	UnlockAndSign(context.Context, *MsgUnlockAndSign) (*MsgUnlockAndSignResponse, error)
	DisableVault(context.Context, *MsgDisableVault) (*MsgDisableVaultResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) SetupVault(context.Context, *MsgSetupVault) (*MsgSetupVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupVault not implemented")
}
func (UnimplementedMsgServer) ConfirmVault(context.Context, *MsgConfirmVault) (*MsgConfirmVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmVault not implemented")
}
func (UnimplementedMsgServer) UnlockAndSign(context.Context, *MsgUnlockAndSign) (*MsgUnlockAndSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockAndSign not implemented")
}
func (UnimplementedMsgServer) DisableVault(context.Context, *MsgDisableVault) (*MsgDisableVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableVault not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_SetupVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetupVault)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetupVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetupVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetupVault(ctx, req.(*MsgSetupVault))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConfirmVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfirmVault)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfirmVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ConfirmVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfirmVault(ctx, req.(*MsgConfirmVault))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnlockAndSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnlockAndSign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnlockAndSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UnlockAndSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnlockAndSign(ctx, req.(*MsgUnlockAndSign))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DisableVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDisableVault)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DisableVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DisableVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DisableVault(ctx, req.(*MsgDisableVault))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketplace.vault.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetupVault",
			Handler:    _Msg_SetupVault_Handler,
		},
		{
			MethodName: "ConfirmVault",
			Handler:    _Msg_ConfirmVault_Handler,
		},
		{
			MethodName: "UnlockAndSign",
			Handler:    _Msg_UnlockAndSign_Handler,
		},
		{
			MethodName: "DisableVault",
			Handler:    _Msg_DisableVault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace/vault/v1/tx.proto",
}
