package types

import (
	"bytes"
	"compress/gzip"
	"io"

	gproto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"

	msg "cosmossdk.io/api/cosmos/msg/v1"
)

// runtime shim: convert the compiled gzipped FileDescriptor (generated by
// protoc-gen-gogo) into a protoreflect FileDescriptor, set the
// (cosmos.msg.v1.service)=true extension on the Msg service, and register
// the file in the global protoregistry so the SDK can find it at runtime.
func init() {
	// fileDescriptor_62733f43e31364a6 is generated in tx.pb.go
	var gz = fileDescriptor_62733f43e31364a6

	// ungzip
	r, err := gzip.NewReader(bytes.NewReader(gz))
	if err != nil {
		return
	}
	defer r.Close()
	raw, err := io.ReadAll(r)
	if err != nil {
		return
	}

	var fdProto descriptorpb.FileDescriptorProto
	if err := gproto.Unmarshal(raw, &fdProto); err != nil {
		return
	}

	// set extension on Msg service options (best-effort)
	for i := range fdProto.Service {
		if fdProto.Service[i].GetName() == "Msg" {
			if fdProto.Service[i].Options == nil {
				fdProto.Service[i].Options = &descriptorpb.ServiceOptions{}
			}
			gproto.SetExtension(fdProto.Service[i].Options, msg.E_Service, true)
		}
	}

	if f, err := protodesc.NewFile(&fdProto, protoregistry.GlobalFiles); err == nil {
		_ = protoregistry.GlobalFiles.RegisterFile(f)
	}
}
