// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketplace/mallpoints/v1/conversion_window.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConversionWindow defines the ConversionWindow message.
type ConversionWindow struct {
	IsOpen       bool   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	CurrentMonth uint64 `protobuf:"varint,2,opt,name=current_month,json=currentMonth,proto3" json:"current_month,omitempty"`
	NextOpening  uint64 `protobuf:"varint,3,opt,name=next_opening,json=nextOpening,proto3" json:"next_opening,omitempty"`
}

func (m *ConversionWindow) Reset()         { *m = ConversionWindow{} }
func (m *ConversionWindow) String() string { return proto.CompactTextString(m) }
func (*ConversionWindow) ProtoMessage()    {}
func (*ConversionWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_995ff3dcfefa5a15, []int{0}
}
func (m *ConversionWindow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConversionWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConversionWindow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConversionWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversionWindow.Merge(m, src)
}
func (m *ConversionWindow) XXX_Size() int {
	return m.Size()
}
func (m *ConversionWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversionWindow.DiscardUnknown(m)
}

var xxx_messageInfo_ConversionWindow proto.InternalMessageInfo

func (m *ConversionWindow) GetIsOpen() bool {
	if m != nil {
		return m.IsOpen
	}
	return false
}

func (m *ConversionWindow) GetCurrentMonth() uint64 {
	if m != nil {
		return m.CurrentMonth
	}
	return 0
}

func (m *ConversionWindow) GetNextOpening() uint64 {
	if m != nil {
		return m.NextOpening
	}
	return 0
}

func init() {
	proto.RegisterType((*ConversionWindow)(nil), "marketplace.mallpoints.v1.ConversionWindow")
}

func init() {
	proto.RegisterFile("marketplace/mallpoints/v1/conversion_window.proto", fileDescriptor_995ff3dcfefa5a15)
}

var fileDescriptor_995ff3dcfefa5a15 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xcc, 0x4d, 0x2c, 0xca,
	0x4e, 0x2d, 0x29, 0xc8, 0x49, 0x4c, 0x4e, 0xd5, 0xcf, 0x4d, 0xcc, 0xc9, 0x29, 0xc8, 0xcf, 0xcc,
	0x2b, 0x29, 0xd6, 0x2f, 0x33, 0xd4, 0x4f, 0xce, 0xcf, 0x2b, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf,
	0x8b, 0x2f, 0xcf, 0xcc, 0x4b, 0xc9, 0x2f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x44,
	0xd2, 0xa2, 0x87, 0xd0, 0xa2, 0x57, 0x66, 0xa8, 0x54, 0xcc, 0x25, 0xe0, 0x0c, 0xd7, 0x15, 0x0e,
	0xd6, 0x24, 0x24, 0xce, 0xc5, 0x9e, 0x59, 0x1c, 0x9f, 0x5f, 0x90, 0x9a, 0x27, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x11, 0xc4, 0x96, 0x59, 0xec, 0x5f, 0x90, 0x9a, 0x27, 0xa4, 0xcc, 0xc5, 0x9b, 0x5c,
	0x5a, 0x54, 0x94, 0x9a, 0x57, 0x12, 0x9f, 0x9b, 0x9f, 0x57, 0x92, 0x21, 0xc1, 0xa4, 0xc0, 0xa8,
	0xc1, 0x12, 0xc4, 0x03, 0x15, 0xf4, 0x05, 0x89, 0x09, 0x29, 0x72, 0xf1, 0xe4, 0xa5, 0x56, 0x94,
	0x80, 0xf5, 0x67, 0xe6, 0xa5, 0x4b, 0x30, 0x83, 0xd5, 0x70, 0x83, 0xc4, 0xfc, 0x21, 0x42, 0x4e,
	0xee, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7,
	0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xa5, 0x9b, 0x9e, 0x59, 0x92,
	0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x5f, 0x92, 0x5b, 0xa0, 0x8f, 0xec, 0xd7, 0x0a, 0x64,
	0xdf, 0x96, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0xfd, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x87, 0x5d, 0xb9, 0x2a, 0x14, 0x01, 0x00, 0x00,
}

func (m *ConversionWindow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConversionWindow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConversionWindow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextOpening != 0 {
		i = encodeVarintConversionWindow(dAtA, i, uint64(m.NextOpening))
		i--
		dAtA[i] = 0x18
	}
	if m.CurrentMonth != 0 {
		i = encodeVarintConversionWindow(dAtA, i, uint64(m.CurrentMonth))
		i--
		dAtA[i] = 0x10
	}
	if m.IsOpen {
		i--
		if m.IsOpen {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintConversionWindow(dAtA []byte, offset int, v uint64) int {
	offset -= sovConversionWindow(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ConversionWindow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsOpen {
		n += 2
	}
	if m.CurrentMonth != 0 {
		n += 1 + sovConversionWindow(uint64(m.CurrentMonth))
	}
	if m.NextOpening != 0 {
		n += 1 + sovConversionWindow(uint64(m.NextOpening))
	}
	return n
}

func sovConversionWindow(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConversionWindow(x uint64) (n int) {
	return sovConversionWindow(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConversionWindow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConversionWindow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConversionWindow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConversionWindow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsOpen", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConversionWindow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsOpen = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentMonth", wireType)
			}
			m.CurrentMonth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConversionWindow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentMonth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextOpening", wireType)
			}
			m.NextOpening = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConversionWindow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextOpening |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConversionWindow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConversionWindow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConversionWindow(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConversionWindow
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConversionWindow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConversionWindow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConversionWindow
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConversionWindow
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConversionWindow
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConversionWindow        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConversionWindow          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConversionWindow = fmt.Errorf("proto: unexpected end of group")
)
