// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketplace/mlcoin/v1/liquidity_pool.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LiquidityPool represents a single liquidity pool
type LiquidityPool struct {
	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token0         string `protobuf:"bytes,3,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1         string `protobuf:"bytes,4,opt,name=token1,proto3" json:"token1,omitempty"`
	Reserve0       string `protobuf:"bytes,5,opt,name=reserve0,proto3" json:"reserve0,omitempty"`
	Reserve1       string `protobuf:"bytes,6,opt,name=reserve1,proto3" json:"reserve1,omitempty"`
	Tvl            string `protobuf:"bytes,7,opt,name=tvl,proto3" json:"tvl,omitempty"`
	Apy            string `protobuf:"bytes,8,opt,name=apy,proto3" json:"apy,omitempty"`
	Volume24H      string `protobuf:"bytes,9,opt,name=volume24h,proto3" json:"volume24h,omitempty"`
	Fee            string `protobuf:"bytes,10,opt,name=fee,proto3" json:"fee,omitempty"`
	TotalLiquidity string `protobuf:"bytes,11,opt,name=total_liquidity,json=totalLiquidity,proto3" json:"total_liquidity,omitempty"`
}

func (m *LiquidityPool) Reset()         { *m = LiquidityPool{} }
func (m *LiquidityPool) String() string { return proto.CompactTextString(m) }
func (*LiquidityPool) ProtoMessage()    {}
func (*LiquidityPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_c754867ef121c582, []int{0}
}
func (m *LiquidityPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityPool.Merge(m, src)
}
func (m *LiquidityPool) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityPool) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityPool.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityPool proto.InternalMessageInfo

func (m *LiquidityPool) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LiquidityPool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LiquidityPool) GetToken0() string {
	if m != nil {
		return m.Token0
	}
	return ""
}

func (m *LiquidityPool) GetToken1() string {
	if m != nil {
		return m.Token1
	}
	return ""
}

func (m *LiquidityPool) GetReserve0() string {
	if m != nil {
		return m.Reserve0
	}
	return ""
}

func (m *LiquidityPool) GetReserve1() string {
	if m != nil {
		return m.Reserve1
	}
	return ""
}

func (m *LiquidityPool) GetTvl() string {
	if m != nil {
		return m.Tvl
	}
	return ""
}

func (m *LiquidityPool) GetApy() string {
	if m != nil {
		return m.Apy
	}
	return ""
}

func (m *LiquidityPool) GetVolume24H() string {
	if m != nil {
		return m.Volume24H
	}
	return ""
}

func (m *LiquidityPool) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *LiquidityPool) GetTotalLiquidity() string {
	if m != nil {
		return m.TotalLiquidity
	}
	return ""
}

// LiquidityPoolState defines the state of liquidity pools
type LiquidityPoolState struct {
	Pools []LiquidityPool `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools"`
}

func (m *LiquidityPoolState) Reset()         { *m = LiquidityPoolState{} }
func (m *LiquidityPoolState) String() string { return proto.CompactTextString(m) }
func (*LiquidityPoolState) ProtoMessage()    {}
func (*LiquidityPoolState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c754867ef121c582, []int{1}
}
func (m *LiquidityPoolState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityPoolState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityPoolState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityPoolState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityPoolState.Merge(m, src)
}
func (m *LiquidityPoolState) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityPoolState) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityPoolState.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityPoolState proto.InternalMessageInfo

func (m *LiquidityPoolState) GetPools() []LiquidityPool {
	if m != nil {
		return m.Pools
	}
	return nil
}

func init() {
	proto.RegisterType((*LiquidityPool)(nil), "marketplace.mlcoin.v1.LiquidityPool")
	proto.RegisterType((*LiquidityPoolState)(nil), "marketplace.mlcoin.v1.LiquidityPoolState")
}

func init() {
	proto.RegisterFile("marketplace/mlcoin/v1/liquidity_pool.proto", fileDescriptor_c754867ef121c582)
}

var fileDescriptor_c754867ef121c582 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x14, 0x45, 0xdb, 0x52, 0x10, 0x86, 0x88, 0x3a, 0x51, 0x33, 0x21, 0xa6, 0x12, 0x62, 0x22, 0xba,
	0x68, 0x29, 0xfa, 0x01, 0x06, 0xb7, 0x2e, 0x0c, 0x26, 0x2e, 0xdc, 0x90, 0x01, 0x06, 0x98, 0x30,
	0xed, 0xab, 0x65, 0x68, 0xec, 0x5f, 0xb8, 0xf4, 0x93, 0x58, 0xb2, 0x74, 0x65, 0x0c, 0xfc, 0x88,
	0xe9, 0x54, 0x6a, 0x49, 0xdc, 0x34, 0x77, 0xce, 0xbd, 0xaf, 0x8b, 0xfb, 0x1e, 0xba, 0xf6, 0x68,
	0x38, 0x63, 0x32, 0x10, 0x74, 0xc8, 0x1c, 0x4f, 0x0c, 0x81, 0xfb, 0x4e, 0xe4, 0x3a, 0x82, 0xbf,
	0x2e, 0xf8, 0x88, 0xcb, 0xb8, 0x1f, 0x00, 0x08, 0x3b, 0x08, 0x41, 0x02, 0x3e, 0xc9, 0x65, 0xed,
	0x34, 0x6b, 0x47, 0x6e, 0xfd, 0x88, 0x7a, 0xdc, 0x07, 0x47, 0x7d, 0xd3, 0x64, 0xfd, 0x78, 0x02,
	0x13, 0x50, 0xd2, 0x49, 0x54, 0x4a, 0x9b, 0x1f, 0x06, 0xda, 0x7f, 0xd8, 0xfe, 0xf8, 0x11, 0x40,
	0xe0, 0x1a, 0x32, 0xf8, 0x88, 0xe8, 0x0d, 0xbd, 0x65, 0xf6, 0x0c, 0x3e, 0xc2, 0x18, 0x99, 0x3e,
	0xf5, 0x18, 0x31, 0x1a, 0x7a, 0xab, 0xd2, 0x53, 0x1a, 0x9f, 0xa2, 0x92, 0x84, 0x19, 0xf3, 0xdb,
	0xa4, 0xa0, 0xe8, 0xef, 0x2b, 0xe3, 0x2e, 0x31, 0x73, 0xdc, 0xc5, 0x75, 0x54, 0x0e, 0xd9, 0x9c,
	0x85, 0x11, 0x6b, 0x93, 0xa2, 0x72, 0xb2, 0x77, 0xce, 0x73, 0x49, 0x69, 0xc7, 0x73, 0xf1, 0x21,
	0x2a, 0xc8, 0x48, 0x90, 0x3d, 0x85, 0x13, 0x99, 0x10, 0x1a, 0xc4, 0xa4, 0x9c, 0x12, 0x1a, 0xc4,
	0xf8, 0x0c, 0x55, 0x22, 0x10, 0x0b, 0x8f, 0x75, 0x6e, 0xa7, 0xa4, 0xa2, 0xf8, 0x1f, 0x48, 0xf2,
	0x63, 0xc6, 0x08, 0x4a, 0xf3, 0x63, 0xc6, 0xf0, 0x25, 0x3a, 0x90, 0x20, 0xa9, 0xe8, 0x67, 0x7d,
	0x92, 0xaa, 0x72, 0x6b, 0x0a, 0x67, 0x65, 0x34, 0x9f, 0x11, 0xde, 0x69, 0xe6, 0x49, 0x52, 0xc9,
	0xf0, 0x1d, 0x2a, 0x26, 0xf5, 0xcf, 0x89, 0xde, 0x28, 0xb4, 0xaa, 0x9d, 0x0b, 0xfb, 0xdf, 0x05,
	0xd8, 0x3b, 0x93, 0x5d, 0x73, 0xf9, 0x75, 0xae, 0xf5, 0xd2, 0xc1, 0xee, 0xfd, 0x72, 0x6d, 0xe9,
	0xab, 0xb5, 0xa5, 0x7f, 0xaf, 0x2d, 0xfd, 0x7d, 0x63, 0x69, 0xab, 0x8d, 0xa5, 0x7d, 0x6e, 0x2c,
	0xed, 0xe5, 0x6a, 0xc2, 0xe5, 0x74, 0x31, 0xb0, 0x87, 0xe0, 0x39, 0xd2, 0x0b, 0x9c, 0xfc, 0x1d,
	0xbc, 0x6d, 0x2f, 0x41, 0xc6, 0x01, 0x9b, 0x0f, 0x4a, 0x6a, 0x7d, 0x37, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc9, 0x8a, 0x8f, 0x1f, 0x2c, 0x02, 0x00, 0x00,
}

func (m *LiquidityPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalLiquidity) > 0 {
		i -= len(m.TotalLiquidity)
		copy(dAtA[i:], m.TotalLiquidity)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.TotalLiquidity)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Volume24H) > 0 {
		i -= len(m.Volume24H)
		copy(dAtA[i:], m.Volume24H)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Volume24H)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Apy) > 0 {
		i -= len(m.Apy)
		copy(dAtA[i:], m.Apy)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Apy)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Tvl) > 0 {
		i -= len(m.Tvl)
		copy(dAtA[i:], m.Tvl)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Tvl)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Reserve1) > 0 {
		i -= len(m.Reserve1)
		copy(dAtA[i:], m.Reserve1)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Reserve1)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Reserve0) > 0 {
		i -= len(m.Reserve0)
		copy(dAtA[i:], m.Reserve0)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Reserve0)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Token1) > 0 {
		i -= len(m.Token1)
		copy(dAtA[i:], m.Token1)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Token1)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Token0) > 0 {
		i -= len(m.Token0)
		copy(dAtA[i:], m.Token0)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Token0)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintLiquidityPool(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintLiquidityPool(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LiquidityPoolState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityPoolState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityPoolState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pools) > 0 {
		for iNdEx := len(m.Pools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLiquidityPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidityPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidityPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidityPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLiquidityPool(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.Token0)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.Token1)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.Reserve0)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.Reserve1)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.Tvl)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.Apy)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.Volume24H)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	l = len(m.TotalLiquidity)
	if l > 0 {
		n += 1 + l + sovLiquidityPool(uint64(l))
	}
	return n
}

func (m *LiquidityPoolState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pools) > 0 {
		for _, e := range m.Pools {
			l = e.Size()
			n += 1 + l + sovLiquidityPool(uint64(l))
		}
	}
	return n
}

func sovLiquidityPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidityPool(x uint64) (n int) {
	return sovLiquidityPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidityPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidityPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token0", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token0 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserve0", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reserve0 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserve1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reserve1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tvl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tvl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume24H", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Volume24H = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLiquidity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalLiquidity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidityPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidityPoolState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidityPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityPoolState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityPoolState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pools = append(m.Pools, LiquidityPool{})
			if err := m.Pools[len(m.Pools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidityPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidityPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidityPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidityPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidityPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidityPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidityPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidityPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidityPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidityPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidityPool = fmt.Errorf("proto: unexpected end of group")
)
