// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketplace/mlcoin/v1/emission_state.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EmissionState defines the EmissionState message.
type EmissionState struct {
	TotalSupply  uint64 `protobuf:"varint,1,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	Circulating  uint64 `protobuf:"varint,2,opt,name=circulating,proto3" json:"circulating,omitempty"`
	MonthlyCap   uint64 `protobuf:"varint,3,opt,name=monthly_cap,json=monthlyCap,proto3" json:"monthly_cap,omitempty"`
	DailyLimit   uint64 `protobuf:"varint,4,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	CurrentMonth uint64 `protobuf:"varint,5,opt,name=current_month,json=currentMonth,proto3" json:"current_month,omitempty"`
	CurrentDay   uint64 `protobuf:"varint,6,opt,name=current_day,json=currentDay,proto3" json:"current_day,omitempty"`
}

func (m *EmissionState) Reset()         { *m = EmissionState{} }
func (m *EmissionState) String() string { return proto.CompactTextString(m) }
func (*EmissionState) ProtoMessage()    {}
func (*EmissionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_aac9f0a4418eb8e1, []int{0}
}
func (m *EmissionState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmissionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmissionState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmissionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionState.Merge(m, src)
}
func (m *EmissionState) XXX_Size() int {
	return m.Size()
}
func (m *EmissionState) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionState.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionState proto.InternalMessageInfo

func (m *EmissionState) GetTotalSupply() uint64 {
	if m != nil {
		return m.TotalSupply
	}
	return 0
}

func (m *EmissionState) GetCirculating() uint64 {
	if m != nil {
		return m.Circulating
	}
	return 0
}

func (m *EmissionState) GetMonthlyCap() uint64 {
	if m != nil {
		return m.MonthlyCap
	}
	return 0
}

func (m *EmissionState) GetDailyLimit() uint64 {
	if m != nil {
		return m.DailyLimit
	}
	return 0
}

func (m *EmissionState) GetCurrentMonth() uint64 {
	if m != nil {
		return m.CurrentMonth
	}
	return 0
}

func (m *EmissionState) GetCurrentDay() uint64 {
	if m != nil {
		return m.CurrentDay
	}
	return 0
}

func init() {
	proto.RegisterType((*EmissionState)(nil), "marketplace.mlcoin.v1.EmissionState")
}

func init() {
	proto.RegisterFile("marketplace/mlcoin/v1/emission_state.proto", fileDescriptor_aac9f0a4418eb8e1)
}

var fileDescriptor_aac9f0a4418eb8e1 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0xc6, 0xf1, 0xf8, 0xde, 0xd2, 0xc1, 0x69, 0x97, 0x48, 0x48, 0x9e, 0x4c, 0x81, 0x05, 0x18,
	0x12, 0x55, 0xbc, 0x01, 0x85, 0x0d, 0x16, 0xba, 0xb1, 0x44, 0xa7, 0xae, 0xd5, 0x5a, 0xd8, 0xb1,
	0x95, 0x9c, 0x54, 0xf8, 0x2d, 0x78, 0x2c, 0xc6, 0x8e, 0x0c, 0x0c, 0x28, 0x79, 0x11, 0x14, 0x27,
	0x95, 0xb2, 0xfe, 0xf5, 0x3b, 0x67, 0xf8, 0xe8, 0x9d, 0x81, 0xf2, 0x5d, 0xa2, 0xd3, 0x20, 0x64,
	0x66, 0xb4, 0xb0, 0xaa, 0xc8, 0x0e, 0xcb, 0x4c, 0x1a, 0x55, 0x55, 0xca, 0x16, 0x79, 0x85, 0x80,
	0x32, 0x75, 0xa5, 0x45, 0x9b, 0x9c, 0x8f, 0x6c, 0xda, 0xdb, 0xf4, 0xb0, 0xbc, 0xfa, 0x21, 0x74,
	0xfe, 0x34, 0xf8, 0x75, 0xc7, 0x93, 0x4b, 0x3a, 0x43, 0x8b, 0xa0, 0xf3, 0xaa, 0x76, 0x4e, 0x7b,
	0x46, 0x16, 0xe4, 0x66, 0xf2, 0x1a, 0x87, 0xb6, 0x0e, 0x29, 0x59, 0xd0, 0x58, 0xa8, 0x52, 0xd4,
	0x1a, 0x50, 0x15, 0x3b, 0xf6, 0xaf, 0x17, 0xa3, 0x94, 0x5c, 0xd0, 0xd8, 0xd8, 0x02, 0xf7, 0xda,
	0xe7, 0x02, 0x1c, 0xfb, 0x1f, 0x04, 0x1d, 0xd2, 0x0a, 0x5c, 0x07, 0xb6, 0xa0, 0xb4, 0xcf, 0xb5,
	0x32, 0x0a, 0xd9, 0xa4, 0x07, 0x21, 0x3d, 0x77, 0x25, 0xb9, 0xa6, 0x73, 0x51, 0x97, 0xa5, 0x2c,
	0x30, 0x0f, 0x67, 0xec, 0x2c, 0x90, 0xd9, 0x10, 0x5f, 0xba, 0xd6, 0x7d, 0x39, 0xa1, 0x2d, 0x78,
	0x36, 0xed, 0xbf, 0x0c, 0xe9, 0x11, 0xfc, 0xc3, 0xea, 0xab, 0xe1, 0xe4, 0xd8, 0x70, 0xf2, 0xdb,
	0x70, 0xf2, 0xd9, 0xf2, 0xe8, 0xd8, 0xf2, 0xe8, 0xbb, 0xe5, 0xd1, 0xdb, 0xed, 0x4e, 0xe1, 0xbe,
	0xde, 0xa4, 0xc2, 0x9a, 0x0c, 0x8d, 0xcb, 0xc6, 0x53, 0x7e, 0x9c, 0xc6, 0x44, 0xef, 0x64, 0xb5,
	0x99, 0x86, 0x05, 0xef, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x6f, 0xa7, 0xc8, 0x6f, 0x01,
	0x00, 0x00,
}

func (m *EmissionState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmissionState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmissionState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentDay != 0 {
		i = encodeVarintEmissionState(dAtA, i, uint64(m.CurrentDay))
		i--
		dAtA[i] = 0x30
	}
	if m.CurrentMonth != 0 {
		i = encodeVarintEmissionState(dAtA, i, uint64(m.CurrentMonth))
		i--
		dAtA[i] = 0x28
	}
	if m.DailyLimit != 0 {
		i = encodeVarintEmissionState(dAtA, i, uint64(m.DailyLimit))
		i--
		dAtA[i] = 0x20
	}
	if m.MonthlyCap != 0 {
		i = encodeVarintEmissionState(dAtA, i, uint64(m.MonthlyCap))
		i--
		dAtA[i] = 0x18
	}
	if m.Circulating != 0 {
		i = encodeVarintEmissionState(dAtA, i, uint64(m.Circulating))
		i--
		dAtA[i] = 0x10
	}
	if m.TotalSupply != 0 {
		i = encodeVarintEmissionState(dAtA, i, uint64(m.TotalSupply))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEmissionState(dAtA []byte, offset int, v uint64) int {
	offset -= sovEmissionState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EmissionState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalSupply != 0 {
		n += 1 + sovEmissionState(uint64(m.TotalSupply))
	}
	if m.Circulating != 0 {
		n += 1 + sovEmissionState(uint64(m.Circulating))
	}
	if m.MonthlyCap != 0 {
		n += 1 + sovEmissionState(uint64(m.MonthlyCap))
	}
	if m.DailyLimit != 0 {
		n += 1 + sovEmissionState(uint64(m.DailyLimit))
	}
	if m.CurrentMonth != 0 {
		n += 1 + sovEmissionState(uint64(m.CurrentMonth))
	}
	if m.CurrentDay != 0 {
		n += 1 + sovEmissionState(uint64(m.CurrentDay))
	}
	return n
}

func sovEmissionState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEmissionState(x uint64) (n int) {
	return sovEmissionState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EmissionState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmissionState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmissionState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmissionState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSupply", wireType)
			}
			m.TotalSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmissionState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Circulating", wireType)
			}
			m.Circulating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmissionState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Circulating |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthlyCap", wireType)
			}
			m.MonthlyCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmissionState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonthlyCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyLimit", wireType)
			}
			m.DailyLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmissionState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DailyLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentMonth", wireType)
			}
			m.CurrentMonth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmissionState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentMonth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentDay", wireType)
			}
			m.CurrentDay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmissionState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentDay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEmissionState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEmissionState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEmissionState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEmissionState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmissionState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmissionState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEmissionState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEmissionState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEmissionState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEmissionState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEmissionState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEmissionState = fmt.Errorf("proto: unexpected end of group")
)
