// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketplace/mlcoin/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Admin: set currency rate (rate is scaled by 100, e.g., 13745 = 137.45 KES)
type MsgSetCurrencyRate struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Currency  string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	RateToKes uint64 `protobuf:"varint,3,opt,name=rate_to_kes,json=rateToKes,proto3" json:"rate_to_kes,omitempty"`
}

func (m *MsgSetCurrencyRate) Reset()         { *m = MsgSetCurrencyRate{} }
func (m *MsgSetCurrencyRate) String() string { return proto.CompactTextString(m) }
func (*MsgSetCurrencyRate) ProtoMessage()    {}
func (*MsgSetCurrencyRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{0}
}
func (m *MsgSetCurrencyRate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetCurrencyRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetCurrencyRate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetCurrencyRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetCurrencyRate.Merge(m, src)
}
func (m *MsgSetCurrencyRate) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetCurrencyRate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetCurrencyRate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetCurrencyRate proto.InternalMessageInfo

func (m *MsgSetCurrencyRate) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetCurrencyRate) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *MsgSetCurrencyRate) GetRateToKes() uint64 {
	if m != nil {
		return m.RateToKes
	}
	return 0
}

type MsgSetCurrencyRateResponse struct {
}

func (m *MsgSetCurrencyRateResponse) Reset()         { *m = MsgSetCurrencyRateResponse{} }
func (m *MsgSetCurrencyRateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetCurrencyRateResponse) ProtoMessage()    {}
func (*MsgSetCurrencyRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{1}
}
func (m *MsgSetCurrencyRateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetCurrencyRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetCurrencyRateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetCurrencyRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetCurrencyRateResponse.Merge(m, src)
}
func (m *MsgSetCurrencyRateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetCurrencyRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetCurrencyRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetCurrencyRateResponse proto.InternalMessageInfo

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{2}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{3}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgTransferMallcoin defines the MsgTransferMallcoin message.
type MsgTransferMallcoin struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	To      string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
}

func (m *MsgTransferMallcoin) Reset()         { *m = MsgTransferMallcoin{} }
func (m *MsgTransferMallcoin) String() string { return proto.CompactTextString(m) }
func (*MsgTransferMallcoin) ProtoMessage()    {}
func (*MsgTransferMallcoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{4}
}
func (m *MsgTransferMallcoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferMallcoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferMallcoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferMallcoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferMallcoin.Merge(m, src)
}
func (m *MsgTransferMallcoin) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferMallcoin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferMallcoin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferMallcoin proto.InternalMessageInfo

func (m *MsgTransferMallcoin) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgTransferMallcoin) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MsgTransferMallcoin) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

// MsgTransferMallcoinResponse defines the MsgTransferMallcoinResponse message.
type MsgTransferMallcoinResponse struct {
	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
}

func (m *MsgTransferMallcoinResponse) Reset()         { *m = MsgTransferMallcoinResponse{} }
func (m *MsgTransferMallcoinResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferMallcoinResponse) ProtoMessage()    {}
func (*MsgTransferMallcoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{5}
}
func (m *MsgTransferMallcoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferMallcoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferMallcoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferMallcoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferMallcoinResponse.Merge(m, src)
}
func (m *MsgTransferMallcoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferMallcoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferMallcoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferMallcoinResponse proto.InternalMessageInfo

func (m *MsgTransferMallcoinResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

// MsgBuyMallcoin defines the message for buying Mallcoins with KES.
type MsgBuyMallcoin struct {
	Buyer      string `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	MlcnAmount uint64 `protobuf:"varint,2,opt,name=mlcn_amount,json=mlcnAmount,proto3" json:"mlcn_amount,omitempty"`
}

func (m *MsgBuyMallcoin) Reset()         { *m = MsgBuyMallcoin{} }
func (m *MsgBuyMallcoin) String() string { return proto.CompactTextString(m) }
func (*MsgBuyMallcoin) ProtoMessage()    {}
func (*MsgBuyMallcoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{6}
}
func (m *MsgBuyMallcoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyMallcoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyMallcoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyMallcoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyMallcoin.Merge(m, src)
}
func (m *MsgBuyMallcoin) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyMallcoin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyMallcoin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyMallcoin proto.InternalMessageInfo

func (m *MsgBuyMallcoin) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgBuyMallcoin) GetMlcnAmount() uint64 {
	if m != nil {
		return m.MlcnAmount
	}
	return 0
}

// MsgBuyMallcoinResponse defines the response for buying Mallcoins.
type MsgBuyMallcoinResponse struct {
	TradeId string `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	KesPaid uint64 `protobuf:"varint,2,opt,name=kes_paid,json=kesPaid,proto3" json:"kes_paid,omitempty"`
	Price   uint64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (m *MsgBuyMallcoinResponse) Reset()         { *m = MsgBuyMallcoinResponse{} }
func (m *MsgBuyMallcoinResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBuyMallcoinResponse) ProtoMessage()    {}
func (*MsgBuyMallcoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{7}
}
func (m *MsgBuyMallcoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyMallcoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyMallcoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyMallcoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyMallcoinResponse.Merge(m, src)
}
func (m *MsgBuyMallcoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyMallcoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyMallcoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyMallcoinResponse proto.InternalMessageInfo

func (m *MsgBuyMallcoinResponse) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *MsgBuyMallcoinResponse) GetKesPaid() uint64 {
	if m != nil {
		return m.KesPaid
	}
	return 0
}

func (m *MsgBuyMallcoinResponse) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

// MsgSellMallcoin defines the message for selling Mallcoins for KES.
type MsgSellMallcoin struct {
	Seller     string `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	MlcnAmount uint64 `protobuf:"varint,2,opt,name=mlcn_amount,json=mlcnAmount,proto3" json:"mlcn_amount,omitempty"`
}

func (m *MsgSellMallcoin) Reset()         { *m = MsgSellMallcoin{} }
func (m *MsgSellMallcoin) String() string { return proto.CompactTextString(m) }
func (*MsgSellMallcoin) ProtoMessage()    {}
func (*MsgSellMallcoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{8}
}
func (m *MsgSellMallcoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellMallcoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellMallcoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellMallcoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellMallcoin.Merge(m, src)
}
func (m *MsgSellMallcoin) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellMallcoin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellMallcoin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellMallcoin proto.InternalMessageInfo

func (m *MsgSellMallcoin) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func (m *MsgSellMallcoin) GetMlcnAmount() uint64 {
	if m != nil {
		return m.MlcnAmount
	}
	return 0
}

// MsgSellMallcoinResponse defines the response for selling Mallcoins.
type MsgSellMallcoinResponse struct {
	TradeId     string `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	KesReceived uint64 `protobuf:"varint,2,opt,name=kes_received,json=kesReceived,proto3" json:"kes_received,omitempty"`
	Price       uint64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (m *MsgSellMallcoinResponse) Reset()         { *m = MsgSellMallcoinResponse{} }
func (m *MsgSellMallcoinResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSellMallcoinResponse) ProtoMessage()    {}
func (*MsgSellMallcoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc512b793b984cc, []int{9}
}
func (m *MsgSellMallcoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellMallcoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellMallcoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellMallcoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellMallcoinResponse.Merge(m, src)
}
func (m *MsgSellMallcoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellMallcoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellMallcoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellMallcoinResponse proto.InternalMessageInfo

func (m *MsgSellMallcoinResponse) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *MsgSellMallcoinResponse) GetKesReceived() uint64 {
	if m != nil {
		return m.KesReceived
	}
	return 0
}

func (m *MsgSellMallcoinResponse) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgSetCurrencyRate)(nil), "marketplace.mlcoin.v1.MsgSetCurrencyRate")
	proto.RegisterType((*MsgSetCurrencyRateResponse)(nil), "marketplace.mlcoin.v1.MsgSetCurrencyRateResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "marketplace.mlcoin.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "marketplace.mlcoin.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgTransferMallcoin)(nil), "marketplace.mlcoin.v1.MsgTransferMallcoin")
	proto.RegisterType((*MsgTransferMallcoinResponse)(nil), "marketplace.mlcoin.v1.MsgTransferMallcoinResponse")
	proto.RegisterType((*MsgBuyMallcoin)(nil), "marketplace.mlcoin.v1.MsgBuyMallcoin")
	proto.RegisterType((*MsgBuyMallcoinResponse)(nil), "marketplace.mlcoin.v1.MsgBuyMallcoinResponse")
	proto.RegisterType((*MsgSellMallcoin)(nil), "marketplace.mlcoin.v1.MsgSellMallcoin")
	proto.RegisterType((*MsgSellMallcoinResponse)(nil), "marketplace.mlcoin.v1.MsgSellMallcoinResponse")
}

func init() { proto.RegisterFile("marketplace/mlcoin/v1/tx.proto", fileDescriptor_1fc512b793b984cc) }

var fileDescriptor_1fc512b793b984cc = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xbf, 0x4f, 0xdb, 0x5a,
	0x14, 0x8e, 0x81, 0x04, 0x72, 0x12, 0xf1, 0xde, 0x33, 0x3c, 0x08, 0x7e, 0xaf, 0x86, 0x5a, 0x6d,
	0x45, 0x23, 0x61, 0x97, 0x54, 0x6a, 0xa5, 0x4c, 0x25, 0x4c, 0xa8, 0x8a, 0x84, 0x0c, 0x5d, 0xba,
	0x44, 0x17, 0xfb, 0x60, 0xac, 0xd8, 0xbe, 0xee, 0xbd, 0x37, 0x28, 0x99, 0x5a, 0x75, 0xec, 0xd4,
	0xb1, 0x7f, 0x42, 0x47, 0x86, 0xf6, 0x3f, 0xe8, 0xc0, 0x88, 0x3a, 0x75, 0xaa, 0x2a, 0x18, 0xf8,
	0x37, 0x2a, 0xff, 0x88, 0x49, 0x42, 0x80, 0xa8, 0x4b, 0x94, 0x73, 0xce, 0x77, 0xcf, 0xf9, 0xbe,
	0xe3, 0xcf, 0xd7, 0xa0, 0xfa, 0x84, 0xb5, 0x51, 0x84, 0x1e, 0xb1, 0xd0, 0xf0, 0x3d, 0x8b, 0xba,
	0x81, 0x71, 0xbc, 0x69, 0x88, 0xae, 0x1e, 0x32, 0x2a, 0xa8, 0xfc, 0xef, 0x40, 0x5d, 0x4f, 0xea,
	0xfa, 0xf1, 0xa6, 0xf2, 0x0f, 0xf1, 0xdd, 0x80, 0x1a, 0xf1, 0x6f, 0x82, 0x54, 0x96, 0x2d, 0xca,
	0x7d, 0xca, 0x0d, 0x9f, 0x3b, 0x51, 0x07, 0x9f, 0x3b, 0x69, 0x61, 0x25, 0x29, 0xb4, 0xe2, 0xc8,
	0x48, 0x82, 0xb4, 0xb4, 0xe8, 0x50, 0x87, 0x26, 0xf9, 0xe8, 0x5f, 0x9a, 0xd5, 0xc6, 0x73, 0x0a,
	0x09, 0x23, 0x7e, 0x7a, 0x52, 0xfb, 0x24, 0x81, 0xdc, 0xe4, 0xce, 0x1e, 0x8a, 0xed, 0x0e, 0x63,
	0x18, 0x58, 0x3d, 0x93, 0x08, 0x94, 0x9f, 0x41, 0x91, 0x74, 0xc4, 0x11, 0x65, 0xae, 0xe8, 0x55,
	0xa4, 0x35, 0x69, 0xbd, 0xd8, 0xa8, 0x7c, 0xff, 0xb2, 0xb1, 0x98, 0x4e, 0xdd, 0xb2, 0x6d, 0x86,
	0x9c, 0xef, 0x09, 0xe6, 0x06, 0x8e, 0x79, 0x05, 0x95, 0x15, 0x98, 0xb3, 0xd2, 0x3e, 0x95, 0xa9,
	0xe8, 0x98, 0x99, 0xc5, 0xb2, 0x0a, 0x25, 0x46, 0x04, 0xb6, 0x04, 0x6d, 0xb5, 0x91, 0x57, 0xa6,
	0xd7, 0xa4, 0xf5, 0x19, 0xb3, 0x18, 0xa5, 0xf6, 0xe9, 0x4b, 0xe4, 0xf5, 0xf9, 0xf7, 0x97, 0x27,
	0xd5, 0xab, 0x5e, 0xda, 0xff, 0xa0, 0x5c, 0x67, 0x66, 0x22, 0x0f, 0x69, 0xc0, 0x51, 0xfb, 0x26,
	0xc1, 0x5f, 0x4d, 0xee, 0xbc, 0x0a, 0x6d, 0x22, 0x70, 0x37, 0x96, 0xf4, 0xc7, 0xac, 0x5f, 0x40,
	0x21, 0x59, 0x4a, 0xcc, 0xb9, 0x54, 0xbb, 0xa7, 0x8f, 0x7d, 0x5a, 0x7a, 0x32, 0xa6, 0x51, 0x3c,
	0xfd, 0xb9, 0x9a, 0xfb, 0x7c, 0x79, 0x52, 0x95, 0xcc, 0xf4, 0x5c, 0xfd, 0xf9, 0x30, 0xf7, 0x0f,
	0x97, 0x27, 0xd5, 0x07, 0x83, 0xdb, 0xef, 0xf6, 0xf7, 0x3f, 0x42, 0x59, 0x5b, 0x81, 0xe5, 0x91,
	0x54, 0xa6, 0xf0, 0x2d, 0x2c, 0x34, 0xb9, 0xb3, 0xcf, 0x48, 0xc0, 0x0f, 0x91, 0x35, 0x89, 0x17,
	0x77, 0x90, 0x6b, 0x30, 0x6b, 0x31, 0x24, 0x82, 0xb2, 0x3b, 0x25, 0xf6, 0x81, 0xf2, 0x12, 0x14,
	0x88, 0x4f, 0x3b, 0x81, 0x88, 0x05, 0xce, 0x98, 0x69, 0x24, 0xcf, 0xc3, 0x94, 0xa0, 0xf1, 0x93,
	0x28, 0x9a, 0x53, 0x82, 0xd6, 0xcb, 0x91, 0x8c, 0xfe, 0x29, 0xad, 0x06, 0xff, 0x8d, 0x21, 0xd0,
	0xe7, 0x27, 0x2f, 0x40, 0x5e, 0x74, 0x5b, 0xae, 0x9d, 0xd0, 0x30, 0x67, 0x44, 0x77, 0xc7, 0xd6,
	0x7c, 0x98, 0x6f, 0x72, 0xa7, 0xd1, 0xe9, 0x65, 0x7c, 0x75, 0xc8, 0x1f, 0x74, 0x7a, 0x78, 0x37,
	0xdb, 0x04, 0x26, 0xaf, 0x42, 0xc9, 0xf7, 0xac, 0xa0, 0x35, 0x44, 0x18, 0xa2, 0xd4, 0x56, 0x9c,
	0xa9, 0x43, 0x44, 0x32, 0x01, 0x6b, 0x36, 0x2c, 0x0d, 0x8f, 0xcb, 0xd8, 0xad, 0xc0, 0x9c, 0x60,
	0xc4, 0xc6, 0x2b, 0x82, 0xb3, 0x71, 0xbc, 0x63, 0x47, 0xa5, 0x36, 0xf2, 0x56, 0x48, 0x5c, 0x3b,
	0x6d, 0x3f, 0xdb, 0x46, 0xbe, 0x4b, 0x5c, 0x5b, 0x5e, 0x84, 0x7c, 0xc8, 0x5c, 0x0b, 0x53, 0x77,
	0x26, 0x81, 0xf6, 0x26, 0xb6, 0xda, 0x1e, 0x7a, 0x5e, 0xa6, 0xea, 0x09, 0x14, 0x38, 0x7a, 0xde,
	0x04, 0xb2, 0x52, 0xdc, 0xdd, 0xba, 0x4a, 0x91, 0xae, 0x14, 0xad, 0xf9, 0xb1, 0x2f, 0x06, 0x47,
	0x4e, 0xa2, 0xec, 0x3e, 0x94, 0x23, 0x65, 0x0c, 0x2d, 0x74, 0x8f, 0xb1, 0xaf, 0xae, 0xd4, 0x46,
	0x6e, 0xa6, 0xa9, 0xf1, 0x0a, 0x6b, 0x5f, 0xa7, 0x61, 0xba, 0xc9, 0x1d, 0xf9, 0x10, 0xca, 0x43,
	0x6f, 0xd4, 0xa3, 0x1b, 0xde, 0x84, 0x11, 0xcf, 0x2a, 0xfa, 0x64, 0xb8, 0x4c, 0x03, 0x83, 0xbf,
	0xaf, 0x19, 0xbb, 0x7a, 0x73, 0x8f, 0x51, 0xac, 0x52, 0x9b, 0x1c, 0x9b, 0xcd, 0xb4, 0xa0, 0x34,
	0xe8, 0xcb, 0x87, 0x37, 0xb7, 0x18, 0x80, 0x29, 0x1b, 0x13, 0xc1, 0xb2, 0x21, 0x87, 0x50, 0x1e,
	0xf2, 0xc9, 0x2d, 0x0b, 0x1c, 0xc4, 0xdd, 0xb6, 0xc0, 0x71, 0x26, 0x50, 0xf2, 0xef, 0xa2, 0xfb,
	0xa7, 0xb1, 0x7d, 0x7a, 0xae, 0x4a, 0x67, 0xe7, 0xaa, 0xf4, 0xeb, 0x5c, 0x95, 0x3e, 0x5e, 0xa8,
	0xb9, 0xb3, 0x0b, 0x35, 0xf7, 0xe3, 0x42, 0xcd, 0xbd, 0x7e, 0xec, 0xb8, 0xe2, 0xa8, 0x73, 0xa0,
	0x5b, 0xd4, 0x37, 0x84, 0x1f, 0x1a, 0x63, 0x6f, 0x23, 0xd1, 0x0b, 0x91, 0x1f, 0x14, 0xe2, 0x4f,
	0xc1, 0xd3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x47, 0x8d, 0xe7, 0xc4, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// TransferMallcoin defines the TransferMallcoin RPC.
	TransferMallcoin(ctx context.Context, in *MsgTransferMallcoin, opts ...grpc.CallOption) (*MsgTransferMallcoinResponse, error)
	// BuyMallcoin defines the BuyMallcoin RPC for purchasing MLCN with KES.
	BuyMallcoin(ctx context.Context, in *MsgBuyMallcoin, opts ...grpc.CallOption) (*MsgBuyMallcoinResponse, error)
	// SellMallcoin defines the SellMallcoin RPC for selling MLCN for KES.
	SellMallcoin(ctx context.Context, in *MsgSellMallcoin, opts ...grpc.CallOption) (*MsgSellMallcoinResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/marketplace.mlcoin.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferMallcoin(ctx context.Context, in *MsgTransferMallcoin, opts ...grpc.CallOption) (*MsgTransferMallcoinResponse, error) {
	out := new(MsgTransferMallcoinResponse)
	err := c.cc.Invoke(ctx, "/marketplace.mlcoin.v1.Msg/TransferMallcoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BuyMallcoin(ctx context.Context, in *MsgBuyMallcoin, opts ...grpc.CallOption) (*MsgBuyMallcoinResponse, error) {
	out := new(MsgBuyMallcoinResponse)
	err := c.cc.Invoke(ctx, "/marketplace.mlcoin.v1.Msg/BuyMallcoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SellMallcoin(ctx context.Context, in *MsgSellMallcoin, opts ...grpc.CallOption) (*MsgSellMallcoinResponse, error) {
	out := new(MsgSellMallcoinResponse)
	err := c.cc.Invoke(ctx, "/marketplace.mlcoin.v1.Msg/SellMallcoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// TransferMallcoin defines the TransferMallcoin RPC.
	TransferMallcoin(context.Context, *MsgTransferMallcoin) (*MsgTransferMallcoinResponse, error)
	// BuyMallcoin defines the BuyMallcoin RPC for purchasing MLCN with KES.
	BuyMallcoin(context.Context, *MsgBuyMallcoin) (*MsgBuyMallcoinResponse, error)
	// SellMallcoin defines the SellMallcoin RPC for selling MLCN for KES.
	SellMallcoin(context.Context, *MsgSellMallcoin) (*MsgSellMallcoinResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) TransferMallcoin(ctx context.Context, req *MsgTransferMallcoin) (*MsgTransferMallcoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferMallcoin not implemented")
}
func (*UnimplementedMsgServer) BuyMallcoin(ctx context.Context, req *MsgBuyMallcoin) (*MsgBuyMallcoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyMallcoin not implemented")
}
func (*UnimplementedMsgServer) SellMallcoin(ctx context.Context, req *MsgSellMallcoin) (*MsgSellMallcoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellMallcoin not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketplace.mlcoin.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferMallcoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferMallcoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferMallcoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketplace.mlcoin.v1.Msg/TransferMallcoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferMallcoin(ctx, req.(*MsgTransferMallcoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BuyMallcoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBuyMallcoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BuyMallcoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketplace.mlcoin.v1.Msg/BuyMallcoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BuyMallcoin(ctx, req.(*MsgBuyMallcoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SellMallcoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSellMallcoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SellMallcoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketplace.mlcoin.v1.Msg/SellMallcoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SellMallcoin(ctx, req.(*MsgSellMallcoin))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "marketplace.mlcoin.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "TransferMallcoin",
			Handler:    _Msg_TransferMallcoin_Handler,
		},
		{
			MethodName: "BuyMallcoin",
			Handler:    _Msg_BuyMallcoin_Handler,
		},
		{
			MethodName: "SellMallcoin",
			Handler:    _Msg_SellMallcoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace/mlcoin/v1/tx.proto",
}

func (m *MsgSetCurrencyRate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetCurrencyRate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetCurrencyRate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RateToKes != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RateToKes))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Currency) > 0 {
		i -= len(m.Currency)
		copy(dAtA[i:], m.Currency)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Currency)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetCurrencyRateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetCurrencyRateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetCurrencyRateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferMallcoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferMallcoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferMallcoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintTx(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferMallcoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferMallcoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferMallcoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuyMallcoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyMallcoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyMallcoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MlcnAmount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MlcnAmount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuyMallcoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyMallcoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyMallcoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Price != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x18
	}
	if m.KesPaid != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.KesPaid))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TradeId) > 0 {
		i -= len(m.TradeId)
		copy(dAtA[i:], m.TradeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TradeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSellMallcoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellMallcoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellMallcoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MlcnAmount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MlcnAmount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSellMallcoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellMallcoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellMallcoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Price != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x18
	}
	if m.KesReceived != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.KesReceived))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TradeId) > 0 {
		i -= len(m.TradeId)
		copy(dAtA[i:], m.TradeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TradeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetCurrencyRate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Currency)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RateToKes != 0 {
		n += 1 + sovTx(uint64(m.RateToKes))
	}
	return n
}

func (m *MsgSetCurrencyRateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferMallcoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTransferMallcoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBuyMallcoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MlcnAmount != 0 {
		n += 1 + sovTx(uint64(m.MlcnAmount))
	}
	return n
}

func (m *MsgBuyMallcoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TradeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.KesPaid != 0 {
		n += 1 + sovTx(uint64(m.KesPaid))
	}
	if m.Price != 0 {
		n += 1 + sovTx(uint64(m.Price))
	}
	return n
}

func (m *MsgSellMallcoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MlcnAmount != 0 {
		n += 1 + sovTx(uint64(m.MlcnAmount))
	}
	return n
}

func (m *MsgSellMallcoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TradeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.KesReceived != 0 {
		n += 1 + sovTx(uint64(m.KesReceived))
	}
	if m.Price != 0 {
		n += 1 + sovTx(uint64(m.Price))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetCurrencyRate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetCurrencyRate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetCurrencyRate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Currency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateToKes", wireType)
			}
			m.RateToKes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RateToKes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetCurrencyRateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetCurrencyRateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetCurrencyRateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferMallcoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferMallcoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferMallcoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferMallcoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferMallcoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferMallcoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyMallcoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyMallcoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyMallcoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MlcnAmount", wireType)
			}
			m.MlcnAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MlcnAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyMallcoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyMallcoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyMallcoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KesPaid", wireType)
			}
			m.KesPaid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KesPaid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellMallcoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellMallcoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellMallcoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MlcnAmount", wireType)
			}
			m.MlcnAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MlcnAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellMallcoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellMallcoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellMallcoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KesReceived", wireType)
			}
			m.KesReceived = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KesReceived |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
