// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/sovereign/sovereign.proto

package types

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FounderCap struct {
	TotalCap             uint64                 `protobuf:"varint,1,opt,name=total_cap,json=totalCap,proto3" json:"total_cap,omitempty"`
	InitialTransferCap   uint64                 `protobuf:"varint,2,opt,name=initial_transfer_cap,json=initialTransferCap,proto3" json:"initial_transfer_cap,omitempty"`
	CapStart             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=cap_start,json=capStart,proto3" json:"cap_start,omitempty"`
	CapEnd               *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cap_end,json=capEnd,proto3" json:"cap_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FounderCap) Reset()         { *m = FounderCap{} }
func (m *FounderCap) String() string { return proto.CompactTextString(m) }
func (*FounderCap) ProtoMessage()    {}
func (*FounderCap) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfe72d7457cf6a21, []int{0}
}
func (m *FounderCap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FounderCap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FounderCap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FounderCap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FounderCap.Merge(m, src)
}
func (m *FounderCap) XXX_Size() int {
	return m.Size()
}
func (m *FounderCap) XXX_DiscardUnknown() {
	xxx_messageInfo_FounderCap.DiscardUnknown(m)
}

var xxx_messageInfo_FounderCap proto.InternalMessageInfo

func (m *FounderCap) GetTotalCap() uint64 {
	if m != nil {
		return m.TotalCap
	}
	return 0
}

func (m *FounderCap) GetInitialTransferCap() uint64 {
	if m != nil {
		return m.InitialTransferCap
	}
	return 0
}

func (m *FounderCap) GetCapStart() *timestamppb.Timestamp {
	if m != nil {
		return m.CapStart
	}
	return nil
}

func (m *FounderCap) GetCapEnd() *timestamppb.Timestamp {
	if m != nil {
		return m.CapEnd
	}
	return nil
}

type Lock struct {
	Address              string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	UnlockAt             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=unlock_at,json=unlockAt,proto3" json:"unlock_at,omitempty"`
	Founder              *FounderCap            `protobuf:"bytes,3,opt,name=founder,proto3" json:"founder,omitempty"`
	Exempt               bool                   `protobuf:"varint,4,opt,name=exempt,proto3" json:"exempt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Lock) Reset()         { *m = Lock{} }
func (m *Lock) String() string { return proto.CompactTextString(m) }
func (*Lock) ProtoMessage()    {}
func (*Lock) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfe72d7457cf6a21, []int{1}
}
func (m *Lock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Lock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Lock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Lock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lock.Merge(m, src)
}
func (m *Lock) XXX_Size() int {
	return m.Size()
}
func (m *Lock) XXX_DiscardUnknown() {
	xxx_messageInfo_Lock.DiscardUnknown(m)
}

var xxx_messageInfo_Lock proto.InternalMessageInfo

func (m *Lock) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Lock) GetUnlockAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UnlockAt
	}
	return nil
}

func (m *Lock) GetFounder() *FounderCap {
	if m != nil {
		return m.Founder
	}
	return nil
}

func (m *Lock) GetExempt() bool {
	if m != nil {
		return m.Exempt
	}
	return false
}

type GenesisState struct {
	Locks                []*Lock  `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfe72d7457cf6a21, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetLocks() []*Lock {
	if m != nil {
		return m.Locks
	}
	return nil
}

type QueryLockRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLockRequest) Reset()         { *m = QueryLockRequest{} }
func (m *QueryLockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLockRequest) ProtoMessage()    {}
func (*QueryLockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfe72d7457cf6a21, []int{3}
}
func (m *QueryLockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockRequest.Merge(m, src)
}
func (m *QueryLockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockRequest proto.InternalMessageInfo

func (m *QueryLockRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryLockResponse struct {
	Lock                 *Lock    `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLockResponse) Reset()         { *m = QueryLockResponse{} }
func (m *QueryLockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLockResponse) ProtoMessage()    {}
func (*QueryLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfe72d7457cf6a21, []int{4}
}
func (m *QueryLockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockResponse.Merge(m, src)
}
func (m *QueryLockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockResponse proto.InternalMessageInfo

func (m *QueryLockResponse) GetLock() *Lock {
	if m != nil {
		return m.Lock
	}
	return nil
}

type QueryRemainingCapRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRemainingCapRequest) Reset()         { *m = QueryRemainingCapRequest{} }
func (m *QueryRemainingCapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRemainingCapRequest) ProtoMessage()    {}
func (*QueryRemainingCapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfe72d7457cf6a21, []int{5}
}
func (m *QueryRemainingCapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRemainingCapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRemainingCapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRemainingCapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRemainingCapRequest.Merge(m, src)
}
func (m *QueryRemainingCapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRemainingCapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRemainingCapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRemainingCapRequest proto.InternalMessageInfo

func (m *QueryRemainingCapRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryRemainingCapResponse struct {
	Remaining            uint64                 `protobuf:"varint,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
	CapEnd               *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=cap_end,json=capEnd,proto3" json:"cap_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *QueryRemainingCapResponse) Reset()         { *m = QueryRemainingCapResponse{} }
func (m *QueryRemainingCapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRemainingCapResponse) ProtoMessage()    {}
func (*QueryRemainingCapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfe72d7457cf6a21, []int{6}
}
func (m *QueryRemainingCapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRemainingCapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRemainingCapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRemainingCapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRemainingCapResponse.Merge(m, src)
}
func (m *QueryRemainingCapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRemainingCapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRemainingCapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRemainingCapResponse proto.InternalMessageInfo

func (m *QueryRemainingCapResponse) GetRemaining() uint64 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *QueryRemainingCapResponse) GetCapEnd() *timestamppb.Timestamp {
	if m != nil {
		return m.CapEnd
	}
	return nil
}

func init() {
	proto.RegisterType((*FounderCap)(nil), "sovereign.FounderCap")
	proto.RegisterType((*Lock)(nil), "sovereign.Lock")
	proto.RegisterType((*GenesisState)(nil), "sovereign.GenesisState")
	proto.RegisterType((*QueryLockRequest)(nil), "sovereign.QueryLockRequest")
	proto.RegisterType((*QueryLockResponse)(nil), "sovereign.QueryLockResponse")
	proto.RegisterType((*QueryRemainingCapRequest)(nil), "sovereign.QueryRemainingCapRequest")
	proto.RegisterType((*QueryRemainingCapResponse)(nil), "sovereign.QueryRemainingCapResponse")
}

func init() { proto.RegisterFile("proto/sovereign/sovereign.proto", fileDescriptor_bfe72d7457cf6a21) }

var fileDescriptor_bfe72d7457cf6a21 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0xdb, 0x34, 0x89, 0xa7, 0x95, 0x80, 0x15, 0x20, 0x93, 0x56, 0x69, 0xe5, 0x82, 0x94,
	0x43, 0x65, 0xa3, 0x14, 0x04, 0x27, 0x24, 0xa8, 0x80, 0x0b, 0x17, 0xdc, 0x9e, 0xe0, 0x10, 0x6d,
	0xec, 0x89, 0xb1, 0x62, 0xef, 0x2e, 0xbb, 0x6b, 0xd4, 0xfe, 0x09, 0x67, 0x6e, 0xfc, 0x09, 0xdc,
	0xf8, 0x04, 0x14, 0x7e, 0x04, 0xed, 0xda, 0x26, 0x56, 0x14, 0x08, 0xb7, 0xec, 0xbc, 0x37, 0x33,
	0xef, 0xbd, 0x89, 0xe1, 0x48, 0x48, 0xae, 0x79, 0xa8, 0xf8, 0x27, 0x94, 0x98, 0xa5, 0x6c, 0xf9,
	0x2b, 0xb0, 0x08, 0x71, 0xff, 0x14, 0x06, 0x47, 0x29, 0xe7, 0x69, 0x8e, 0xa1, 0x05, 0xa6, 0xe5,
	0x2c, 0xd4, 0x59, 0x81, 0x4a, 0xd3, 0x42, 0x54, 0x5c, 0xff, 0xbb, 0x03, 0xf0, 0x8a, 0x97, 0x2c,
	0x41, 0x79, 0x4e, 0x05, 0x39, 0x00, 0x57, 0x73, 0x4d, 0xf3, 0x49, 0x4c, 0x85, 0xe7, 0x1c, 0x3b,
	0xa3, 0x4e, 0xd4, 0xb7, 0x05, 0x03, 0x3e, 0x84, 0xdb, 0x19, 0xcb, 0x74, 0x46, 0xf3, 0x89, 0x96,
	0x94, 0xa9, 0x19, 0x4a, 0xcb, 0xdb, 0xb6, 0x3c, 0x52, 0x63, 0x97, 0x35, 0x64, 0x3a, 0x9e, 0x80,
	0x1b, 0x53, 0x31, 0x51, 0x9a, 0x4a, 0xed, 0xed, 0x1c, 0x3b, 0xa3, 0xbd, 0xf1, 0x20, 0xa8, 0x24,
	0x05, 0x8d, 0xa4, 0xe0, 0xb2, 0x91, 0x14, 0xf5, 0x63, 0x2a, 0x2e, 0x0c, 0x97, 0x9c, 0x41, 0xcf,
	0x34, 0x22, 0x4b, 0xbc, 0xce, 0xc6, 0xb6, 0x6e, 0x4c, 0xc5, 0x4b, 0x96, 0xf8, 0x5f, 0x1c, 0xe8,
	0xbc, 0xe1, 0xf1, 0x9c, 0x78, 0xd0, 0xa3, 0x49, 0x22, 0x51, 0x29, 0xeb, 0xc1, 0x8d, 0x9a, 0xa7,
	0x11, 0x54, 0xb2, 0x9c, 0xc7, 0xf3, 0x09, 0xd5, 0x56, 0xf7, 0x06, 0x41, 0x15, 0xf9, 0xb9, 0x26,
	0x21, 0xf4, 0x66, 0x55, 0x4c, 0xb5, 0x8f, 0x3b, 0xc1, 0x32, 0xf6, 0x65, 0x80, 0x51, 0xc3, 0x22,
	0x77, 0xa1, 0x8b, 0x57, 0x58, 0x08, 0x6d, 0x0d, 0xf4, 0xa3, 0xfa, 0xe5, 0x3f, 0x86, 0xfd, 0xd7,
	0xc8, 0x50, 0x65, 0xea, 0x42, 0x53, 0x8d, 0xe4, 0x01, 0xec, 0x9a, 0x15, 0x46, 0xe9, 0xce, 0x68,
	0x6f, 0x7c, 0xa3, 0x35, 0xd6, 0x78, 0x89, 0x2a, 0xd4, 0x3f, 0x85, 0x9b, 0x6f, 0x4b, 0x94, 0xd7,
	0xb6, 0x86, 0x1f, 0x4b, 0x54, 0xfa, 0xef, 0x36, 0xfd, 0xa7, 0x70, 0xab, 0xc5, 0x56, 0x82, 0x33,
	0x85, 0xe4, 0x04, 0x3a, 0x66, 0x96, 0xe5, 0xae, 0x59, 0x64, 0x41, 0xff, 0x11, 0x78, 0xb6, 0x33,
	0xc2, 0x82, 0x66, 0x2c, 0x63, 0xa9, 0x31, 0xb5, 0x71, 0x1f, 0x83, 0x7b, 0x6b, 0xba, 0xea, 0xbd,
	0x87, 0xe0, 0xca, 0xa6, 0x5e, 0xff, 0xa7, 0x96, 0x85, 0xf6, 0xa5, 0xb7, 0xff, 0xf7, 0xd2, 0xe3,
	0xaf, 0x0e, 0xec, 0xda, 0x85, 0xe4, 0xbc, 0x3e, 0xf9, 0x41, 0xcb, 0xce, 0x6a, 0x50, 0x83, 0xc3,
	0xf5, 0x60, 0xa5, 0xcf, 0xdf, 0x22, 0xef, 0x61, 0xbf, 0xad, 0x9c, 0x9c, 0xac, 0xf2, 0xd7, 0xa4,
	0x31, 0xb8, 0xff, 0x6f, 0x52, 0x33, 0xfc, 0xc5, 0xb3, 0x6f, 0x8b, 0xa1, 0xf3, 0x63, 0x31, 0x74,
	0x7e, 0x2e, 0x86, 0xce, 0xe7, 0x5f, 0xc3, 0xad, 0x77, 0xa7, 0x69, 0xa6, 0x3f, 0x94, 0xd3, 0x20,
	0xe6, 0x45, 0xa8, 0x0b, 0x11, 0x16, 0x54, 0xce, 0x51, 0x8b, 0x9c, 0xc6, 0x18, 0x5e, 0xb5, 0xbe,
	0x6b, 0x7d, 0x2d, 0x50, 0x4d, 0xbb, 0x36, 0x87, 0xb3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x08,
	0x37, 0xe4, 0xff, 0xf7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Lock(ctx context.Context, in *QueryLockRequest, opts ...grpc.CallOption) (*QueryLockResponse, error)
	RemainingCap(ctx context.Context, in *QueryRemainingCapRequest, opts ...grpc.CallOption) (*QueryRemainingCapResponse, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Lock(ctx context.Context, in *QueryLockRequest, opts ...grpc.CallOption) (*QueryLockResponse, error) {
	out := new(QueryLockResponse)
	err := c.cc.Invoke(ctx, "/sovereign.Query/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RemainingCap(ctx context.Context, in *QueryRemainingCapRequest, opts ...grpc.CallOption) (*QueryRemainingCapResponse, error) {
	out := new(QueryRemainingCapResponse)
	err := c.cc.Invoke(ctx, "/sovereign.Query/RemainingCap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Lock(context.Context, *QueryLockRequest) (*QueryLockResponse, error)
	RemainingCap(context.Context, *QueryRemainingCapRequest) (*QueryRemainingCapResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Lock(ctx context.Context, req *QueryLockRequest) (*QueryLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedQueryServer) RemainingCap(ctx context.Context, req *QueryRemainingCapRequest) (*QueryRemainingCapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemainingCap not implemented")
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sovereign.Query/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Lock(ctx, req.(*QueryLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RemainingCap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRemainingCapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RemainingCap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sovereign.Query/RemainingCap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RemainingCap(ctx, req.(*QueryRemainingCapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sovereign.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _Query_Lock_Handler,
		},
		{
			MethodName: "RemainingCap",
			Handler:    _Query_RemainingCap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sovereign/sovereign.proto",
}

func (m *FounderCap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FounderCap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FounderCap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.CapEnd != nil {
		{
			size, err := m.CapEnd.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSovereign(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.CapStart != nil {
		{
			size, err := m.CapStart.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSovereign(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.InitialTransferCap != 0 {
		i = encodeVarintSovereign(dAtA, i, uint64(m.InitialTransferCap))
		i--
		dAtA[i] = 0x10
	}
	if m.TotalCap != 0 {
		i = encodeVarintSovereign(dAtA, i, uint64(m.TotalCap))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Lock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Lock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Lock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Exempt {
		i--
		if m.Exempt {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Founder != nil {
		{
			size, err := m.Founder.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSovereign(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.UnlockAt != nil {
		{
			size, err := m.UnlockAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSovereign(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintSovereign(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSovereign(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintSovereign(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Lock != nil {
		{
			size, err := m.Lock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSovereign(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRemainingCapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRemainingCapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRemainingCapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintSovereign(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRemainingCapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRemainingCapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRemainingCapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.CapEnd != nil {
		{
			size, err := m.CapEnd.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSovereign(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Remaining != 0 {
		i = encodeVarintSovereign(dAtA, i, uint64(m.Remaining))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSovereign(dAtA []byte, offset int, v uint64) int {
	offset -= sovSovereign(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FounderCap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalCap != 0 {
		n += 1 + sovSovereign(uint64(m.TotalCap))
	}
	if m.InitialTransferCap != 0 {
		n += 1 + sovSovereign(uint64(m.InitialTransferCap))
	}
	if m.CapStart != nil {
		l = m.CapStart.Size()
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.CapEnd != nil {
		l = m.CapEnd.Size()
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Lock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.UnlockAt != nil {
		l = m.UnlockAt.Size()
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.Founder != nil {
		l = m.Founder.Size()
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.Exempt {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovSovereign(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *QueryLockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *QueryLockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Lock != nil {
		l = m.Lock.Size()
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *QueryRemainingCapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *QueryRemainingCapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Remaining != 0 {
		n += 1 + sovSovereign(uint64(m.Remaining))
	}
	if m.CapEnd != nil {
		l = m.CapEnd.Size()
		n += 1 + l + sovSovereign(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSovereign(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSovereign(x uint64) (n int) {
	return sovSovereign(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FounderCap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereign
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FounderCap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FounderCap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCap", wireType)
			}
			m.TotalCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialTransferCap", wireType)
			}
			m.InitialTransferCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialTransferCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapStart", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CapStart == nil {
				m.CapStart = &timestamppb.Timestamp{}
			}
			if err := m.CapStart.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapEnd", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CapEnd == nil {
				m.CapEnd = &timestamppb.Timestamp{}
			}
			if err := m.CapEnd.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereign(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSovereign
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Lock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereign
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Lock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Lock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UnlockAt == nil {
				m.UnlockAt = &timestamppb.Timestamp{}
			}
			if err := m.UnlockAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Founder", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Founder == nil {
				m.Founder = &FounderCap{}
			}
			if err := m.Founder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exempt", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exempt = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipSovereign(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSovereign
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereign
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, &Lock{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereign(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSovereign
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereign
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereign(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSovereign
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereign
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Lock == nil {
				m.Lock = &Lock{}
			}
			if err := m.Lock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereign(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSovereign
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRemainingCapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereign
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRemainingCapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRemainingCapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereign(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSovereign
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRemainingCapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereign
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRemainingCapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRemainingCapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remaining", wireType)
			}
			m.Remaining = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Remaining |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapEnd", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereign
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereign
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CapEnd == nil {
				m.CapEnd = &timestamppb.Timestamp{}
			}
			if err := m.CapEnd.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereign(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSovereign
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSovereign(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSovereign
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSovereign
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSovereign
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSovereign
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSovereign
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSovereign        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSovereign          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSovereign = fmt.Errorf("proto: unexpected end of group")
)
