// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketplace/badge/v1/user_badge.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// UserBadge defines the UserBadge message.
type UserBadge struct {
	Index      string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Address    string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	HasBadge   bool   `protobuf:"varint,3,opt,name=has_badge,json=hasBadge,proto3" json:"has_badge,omitempty"`
	IssuedDate uint64 `protobuf:"varint,4,opt,name=issued_date,json=issuedDate,proto3" json:"issued_date,omitempty"`
	BadgeType  string `protobuf:"bytes,5,opt,name=badge_type,json=badgeType,proto3" json:"badge_type,omitempty"`
}

func (m *UserBadge) Reset()         { *m = UserBadge{} }
func (m *UserBadge) String() string { return proto.CompactTextString(m) }
func (*UserBadge) ProtoMessage()    {}
func (*UserBadge) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f9ed815a094be1f, []int{0}
}
func (m *UserBadge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserBadge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserBadge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserBadge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBadge.Merge(m, src)
}
func (m *UserBadge) XXX_Size() int {
	return m.Size()
}
func (m *UserBadge) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBadge.DiscardUnknown(m)
}

var xxx_messageInfo_UserBadge proto.InternalMessageInfo

func (m *UserBadge) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *UserBadge) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserBadge) GetHasBadge() bool {
	if m != nil {
		return m.HasBadge
	}
	return false
}

func (m *UserBadge) GetIssuedDate() uint64 {
	if m != nil {
		return m.IssuedDate
	}
	return 0
}

func (m *UserBadge) GetBadgeType() string {
	if m != nil {
		return m.BadgeType
	}
	return ""
}

func init() {
	proto.RegisterType((*UserBadge)(nil), "marketplace.badge.v1.UserBadge")
}

func init() {
	proto.RegisterFile("marketplace/badge/v1/user_badge.proto", fileDescriptor_1f9ed815a094be1f)
}

var fileDescriptor_1f9ed815a094be1f = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0xda, 0x6a, 0x33, 0xde, 0x42, 0x0f, 0x0b, 0xe2, 0x1a, 0x04, 0x21, 0xa7, 0x2c,
	0xc5, 0x37, 0x08, 0x3e, 0x41, 0xd0, 0x8b, 0x97, 0xb0, 0xe9, 0x0e, 0x4d, 0xd0, 0x98, 0x65, 0x67,
	0x53, 0xda, 0xb7, 0xf0, 0xe8, 0x23, 0x79, 0xec, 0xd1, 0xa3, 0x24, 0x2f, 0x22, 0xdd, 0x55, 0xe8,
	0xf1, 0xff, 0x76, 0xe7, 0x1b, 0xe6, 0x87, 0xfb, 0x4e, 0xd9, 0x57, 0x74, 0xe6, 0x4d, 0xad, 0x51,
	0xd6, 0x4a, 0x6f, 0x50, 0x6e, 0x57, 0x72, 0x20, 0xb4, 0x95, 0x4f, 0xb9, 0xb1, 0xbd, 0xeb, 0x93,
	0xe5, 0xc9, 0xb7, 0x3c, 0x3c, 0x6c, 0x57, 0x77, 0x9f, 0x0c, 0xe2, 0x67, 0x42, 0x5b, 0x1c, 0x41,
	0xb2, 0x84, 0x79, 0xfb, 0xae, 0x71, 0xc7, 0x59, 0xca, 0xb2, 0xb8, 0x0c, 0x21, 0xe1, 0x70, 0xa9,
	0xb4, 0xb6, 0x48, 0xc4, 0xcf, 0x3c, 0xff, 0x8f, 0xc9, 0x35, 0xc4, 0x8d, 0xa2, 0xb0, 0x86, 0x9f,
	0xa7, 0x2c, 0x5b, 0x94, 0x8b, 0x46, 0x51, 0x90, 0xdd, 0xc2, 0x55, 0x4b, 0x34, 0xa0, 0xae, 0xb4,
	0x72, 0xc8, 0x67, 0x29, 0xcb, 0x66, 0x25, 0x04, 0xf4, 0xa8, 0x1c, 0x26, 0x37, 0x00, 0x7e, 0xb2,
	0x72, 0x7b, 0x83, 0x7c, 0xee, 0xd5, 0xb1, 0x27, 0x4f, 0x7b, 0x83, 0x45, 0xf1, 0x35, 0x0a, 0x76,
	0x18, 0x05, 0xfb, 0x19, 0x05, 0xfb, 0x98, 0x44, 0x74, 0x98, 0x44, 0xf4, 0x3d, 0x89, 0xe8, 0x25,
	0xdb, 0xb4, 0xae, 0x19, 0xea, 0x7c, 0xdd, 0x77, 0xd2, 0x75, 0x46, 0x9e, 0x16, 0xb0, 0xfb, 0xab,
	0xe0, 0xe8, 0xa4, 0xfa, 0xc2, 0xdf, 0xfe, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x45, 0x59, 0xb4,
	0x59, 0x24, 0x01, 0x00, 0x00,
}

func (m *UserBadge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserBadge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserBadge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BadgeType) > 0 {
		i -= len(m.BadgeType)
		copy(dAtA[i:], m.BadgeType)
		i = encodeVarintUserBadge(dAtA, i, uint64(len(m.BadgeType)))
		i--
		dAtA[i] = 0x2a
	}
	if m.IssuedDate != 0 {
		i = encodeVarintUserBadge(dAtA, i, uint64(m.IssuedDate))
		i--
		dAtA[i] = 0x20
	}
	if m.HasBadge {
		i--
		if m.HasBadge {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintUserBadge(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintUserBadge(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintUserBadge(dAtA []byte, offset int, v uint64) int {
	offset -= sovUserBadge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UserBadge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovUserBadge(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovUserBadge(uint64(l))
	}
	if m.HasBadge {
		n += 2
	}
	if m.IssuedDate != 0 {
		n += 1 + sovUserBadge(uint64(m.IssuedDate))
	}
	l = len(m.BadgeType)
	if l > 0 {
		n += 1 + l + sovUserBadge(uint64(l))
	}
	return n
}

func sovUserBadge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUserBadge(x uint64) (n int) {
	return sovUserBadge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserBadge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUserBadge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserBadge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserBadge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserBadge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserBadge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserBadge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserBadge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserBadge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserBadge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasBadge", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserBadge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasBadge = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuedDate", wireType)
			}
			m.IssuedDate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserBadge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuedDate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BadgeType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserBadge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserBadge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserBadge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BadgeType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUserBadge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUserBadge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUserBadge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUserBadge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserBadge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserBadge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUserBadge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUserBadge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUserBadge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUserBadge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUserBadge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUserBadge = fmt.Errorf("proto: unexpected end of group")
)
