// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketplace/mlcoin/v1/market.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MarketPrice tracks current buy/sell prices and trading volume
type MarketPrice struct {
	// buy_price is the current price to buy 1 MLCN in KES (scaled by 100, e.g., 62 = 0.62 KES)
	BuyPrice uint64 `protobuf:"varint,1,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	// sell_price is the current price to sell 1 MLCN in KES (scaled by 100, e.g., 58 = 0.58 KES)
	SellPrice uint64 `protobuf:"varint,2,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	// total_buy_volume tracks total MLCN bought
	TotalBuyVolume uint64 `protobuf:"varint,3,opt,name=total_buy_volume,json=totalBuyVolume,proto3" json:"total_buy_volume,omitempty"`
	// total_sell_volume tracks total MLCN sold
	TotalSellVolume uint64 `protobuf:"varint,4,opt,name=total_sell_volume,json=totalSellVolume,proto3" json:"total_sell_volume,omitempty"`
	// last_update_height is the block height of last price update
	LastUpdateHeight uint64 `protobuf:"varint,5,opt,name=last_update_height,json=lastUpdateHeight,proto3" json:"last_update_height,omitempty"`
}

func (m *MarketPrice) Reset()         { *m = MarketPrice{} }
func (m *MarketPrice) String() string { return proto.CompactTextString(m) }
func (*MarketPrice) ProtoMessage()    {}
func (*MarketPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_990a7d9ce45b9250, []int{0}
}
func (m *MarketPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarketPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarketPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MarketPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketPrice.Merge(m, src)
}
func (m *MarketPrice) XXX_Size() int {
	return m.Size()
}
func (m *MarketPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketPrice.DiscardUnknown(m)
}

var xxx_messageInfo_MarketPrice proto.InternalMessageInfo

func (m *MarketPrice) GetBuyPrice() uint64 {
	if m != nil {
		return m.BuyPrice
	}
	return 0
}

func (m *MarketPrice) GetSellPrice() uint64 {
	if m != nil {
		return m.SellPrice
	}
	return 0
}

func (m *MarketPrice) GetTotalBuyVolume() uint64 {
	if m != nil {
		return m.TotalBuyVolume
	}
	return 0
}

func (m *MarketPrice) GetTotalSellVolume() uint64 {
	if m != nil {
		return m.TotalSellVolume
	}
	return 0
}

func (m *MarketPrice) GetLastUpdateHeight() uint64 {
	if m != nil {
		return m.LastUpdateHeight
	}
	return 0
}

// KesBalance tracks user's KES balance for marketplace
type KesBalance struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance uint64 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (m *KesBalance) Reset()         { *m = KesBalance{} }
func (m *KesBalance) String() string { return proto.CompactTextString(m) }
func (*KesBalance) ProtoMessage()    {}
func (*KesBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_990a7d9ce45b9250, []int{1}
}
func (m *KesBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KesBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KesBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KesBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KesBalance.Merge(m, src)
}
func (m *KesBalance) XXX_Size() int {
	return m.Size()
}
func (m *KesBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_KesBalance.DiscardUnknown(m)
}

var xxx_messageInfo_KesBalance proto.InternalMessageInfo

func (m *KesBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *KesBalance) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// Trade represents a completed buy/sell order
type Trade struct {
	TxId        string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Trader      string `protobuf:"bytes,2,opt,name=trader,proto3" json:"trader,omitempty"`
	TradeType   string `protobuf:"bytes,3,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	MlcnAmount  uint64 `protobuf:"varint,4,opt,name=mlcn_amount,json=mlcnAmount,proto3" json:"mlcn_amount,omitempty"`
	KesAmount   uint64 `protobuf:"varint,5,opt,name=kes_amount,json=kesAmount,proto3" json:"kes_amount,omitempty"`
	Price       uint64 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp   int64  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockHeight uint64 `protobuf:"varint,8,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_990a7d9ce45b9250, []int{2}
}
func (m *Trade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return m.Size()
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Trade) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *Trade) GetTradeType() string {
	if m != nil {
		return m.TradeType
	}
	return ""
}

func (m *Trade) GetMlcnAmount() uint64 {
	if m != nil {
		return m.MlcnAmount
	}
	return 0
}

func (m *Trade) GetKesAmount() uint64 {
	if m != nil {
		return m.KesAmount
	}
	return 0
}

func (m *Trade) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Trade) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// CurrencyRate represents exchange rate of a currency to KES (scaled by 100)
type CurrencyRate struct {
	Currency    string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	RateToKes   uint64 `protobuf:"varint,2,opt,name=rate_to_kes,json=rateToKes,proto3" json:"rate_to_kes,omitempty"`
	LastUpdated uint64 `protobuf:"varint,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (m *CurrencyRate) Reset()         { *m = CurrencyRate{} }
func (m *CurrencyRate) String() string { return proto.CompactTextString(m) }
func (*CurrencyRate) ProtoMessage()    {}
func (*CurrencyRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_990a7d9ce45b9250, []int{3}
}
func (m *CurrencyRate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrencyRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrencyRate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrencyRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyRate.Merge(m, src)
}
func (m *CurrencyRate) XXX_Size() int {
	return m.Size()
}
func (m *CurrencyRate) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyRate.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyRate proto.InternalMessageInfo

func (m *CurrencyRate) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CurrencyRate) GetRateToKes() uint64 {
	if m != nil {
		return m.RateToKes
	}
	return 0
}

func (m *CurrencyRate) GetLastUpdated() uint64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func init() {
	proto.RegisterType((*MarketPrice)(nil), "marketplace.mlcoin.v1.MarketPrice")
	proto.RegisterType((*KesBalance)(nil), "marketplace.mlcoin.v1.KesBalance")
	proto.RegisterType((*Trade)(nil), "marketplace.mlcoin.v1.Trade")
	proto.RegisterType((*CurrencyRate)(nil), "marketplace.mlcoin.v1.CurrencyRate")
}

func init() {
	proto.RegisterFile("marketplace/mlcoin/v1/market.proto", fileDescriptor_990a7d9ce45b9250)
}

var fileDescriptor_990a7d9ce45b9250 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x6b, 0x9a, 0xa4, 0xf1, 0x49, 0x05, 0x65, 0xb8, 0x28, 0xe2, 0x62, 0x4a, 0x56, 0x01,
	0xa1, 0x44, 0x15, 0x2f, 0x00, 0xe9, 0x06, 0x54, 0x21, 0x21, 0x13, 0x58, 0xb0, 0xb1, 0xc6, 0xf6,
	0x51, 0x63, 0x65, 0xc6, 0x63, 0x79, 0xc6, 0x51, 0xfc, 0x16, 0x3c, 0x16, 0x1b, 0xa4, 0x2e, 0x59,
	0xa2, 0x64, 0xc7, 0x53, 0xa0, 0x39, 0x33, 0xa6, 0xd9, 0xf9, 0xff, 0xbf, 0xff, 0x8c, 0x75, 0x2e,
	0x30, 0x91, 0xbc, 0x5e, 0xa3, 0xa9, 0x04, 0xcf, 0x70, 0x2e, 0x45, 0xa6, 0x8a, 0x72, 0xbe, 0xb9,
	0x98, 0x3b, 0x77, 0x56, 0xd5, 0xca, 0x28, 0xf6, 0xe8, 0x20, 0x33, 0x73, 0x99, 0xd9, 0xe6, 0x62,
	0xf2, 0x2b, 0x80, 0xd1, 0x27, 0x22, 0x9f, 0xeb, 0x22, 0x43, 0xf6, 0x14, 0xc2, 0xb4, 0x69, 0x93,
	0xca, 0x8a, 0x71, 0x70, 0x1e, 0x4c, 0x7b, 0xf1, 0x30, 0x6d, 0x5a, 0x07, 0x9f, 0x03, 0x68, 0x14,
	0xc2, 0xd3, 0x3b, 0x44, 0x43, 0xeb, 0x38, 0x3c, 0x85, 0x33, 0xa3, 0x0c, 0x17, 0x89, 0x7d, 0x61,
	0xa3, 0x44, 0x23, 0x71, 0x7c, 0x4c, 0xa1, 0xbb, 0xe4, 0x2f, 0x9a, 0xf6, 0x1b, 0xb9, 0xec, 0x35,
	0xdc, 0x77, 0x49, 0x7a, 0xce, 0x47, 0x7b, 0x14, 0xbd, 0x47, 0xe0, 0x0b, 0x0a, 0xe1, 0xb3, 0x6f,
	0x80, 0x09, 0xae, 0x4d, 0xd2, 0x54, 0x39, 0x37, 0x98, 0xac, 0xb0, 0xb8, 0x5e, 0x99, 0x71, 0x9f,
	0xc2, 0x67, 0x96, 0x7c, 0x25, 0xf0, 0x81, 0xfc, 0xc9, 0x3b, 0x80, 0x2b, 0xd4, 0x0b, 0x2e, 0x78,
	0x99, 0x21, 0x1b, 0xc3, 0x09, 0xcf, 0xf3, 0x1a, 0xb5, 0xa6, 0x5e, 0xc2, 0xb8, 0x93, 0x96, 0xa4,
	0x2e, 0xe4, 0xfb, 0xe8, 0xe4, 0xe4, 0x6f, 0x00, 0xfd, 0x65, 0xcd, 0x73, 0x64, 0x0f, 0xa0, 0x6f,
	0xb6, 0x49, 0x91, 0xfb, 0xda, 0x9e, 0xd9, 0x7e, 0xcc, 0xd9, 0x63, 0x18, 0x18, 0x4b, 0x6b, 0xaa,
	0x0b, 0x63, 0xaf, 0xec, 0x6c, 0xe8, 0x2b, 0x31, 0x6d, 0xe5, 0xda, 0x0e, 0xe3, 0x90, 0x9c, 0x65,
	0x5b, 0x21, 0x7b, 0x01, 0x23, 0x29, 0xb2, 0x32, 0xe1, 0x52, 0x35, 0xa5, 0xf1, 0xbd, 0x82, 0xb5,
	0xde, 0x93, 0x63, 0xeb, 0xd7, 0xa8, 0x3b, 0xee, 0xda, 0x0b, 0xd7, 0xa8, 0x3d, 0x7e, 0x08, 0x7d,
	0x37, 0xf5, 0x01, 0x11, 0x27, 0xd8, 0x33, 0x08, 0x4d, 0x21, 0x51, 0x1b, 0x2e, 0xab, 0xf1, 0xc9,
	0x79, 0x30, 0x3d, 0x8e, 0x6f, 0x0d, 0xf6, 0x12, 0x4e, 0x53, 0xa1, 0xb2, 0x75, 0x37, 0xb3, 0x21,
	0x95, 0x8e, 0xc8, 0xf3, 0xe3, 0x92, 0x70, 0x7a, 0xd9, 0xd4, 0x35, 0x96, 0x59, 0x1b, 0x73, 0x83,
	0xec, 0x09, 0x0c, 0x33, 0xaf, 0x7d, 0xd7, 0xff, 0x35, 0x8b, 0x60, 0x54, 0xdb, 0x0d, 0x18, 0x95,
	0xac, 0x51, 0x77, 0xeb, 0xb7, 0xd6, 0x52, 0x5d, 0xa1, 0xb6, 0xbf, 0x3b, 0x58, 0x54, 0xee, 0x57,
	0x3f, 0xba, 0x5d, 0x51, 0xbe, 0xb8, 0xfc, 0xb9, 0x8b, 0x82, 0x9b, 0x5d, 0x14, 0xfc, 0xd9, 0x45,
	0xc1, 0x8f, 0x7d, 0x74, 0x74, 0xb3, 0x8f, 0x8e, 0x7e, 0xef, 0xa3, 0xa3, 0xef, 0xaf, 0xae, 0x0b,
	0xb3, 0x6a, 0xd2, 0x59, 0xa6, 0xe4, 0xdc, 0xc8, 0x6a, 0x7e, 0x78, 0xd1, 0xdb, 0xee, 0xa6, 0xed,
	0x68, 0x75, 0x3a, 0xa0, 0x83, 0x7e, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x23, 0x2b, 0xd8, 0xdb,
	0xf6, 0x02, 0x00, 0x00,
}

func (m *MarketPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarketPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MarketPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdateHeight != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.LastUpdateHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.TotalSellVolume != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.TotalSellVolume))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalBuyVolume != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.TotalBuyVolume))
		i--
		dAtA[i] = 0x18
	}
	if m.SellPrice != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.SellPrice))
		i--
		dAtA[i] = 0x10
	}
	if m.BuyPrice != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.BuyPrice))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *KesBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KesBalance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KesBalance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Balance != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.Balance))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Trade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Trade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.Timestamp != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x38
	}
	if m.Price != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x30
	}
	if m.KesAmount != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.KesAmount))
		i--
		dAtA[i] = 0x28
	}
	if m.MlcnAmount != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.MlcnAmount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TradeType) > 0 {
		i -= len(m.TradeType)
		copy(dAtA[i:], m.TradeType)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.TradeType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Trader) > 0 {
		i -= len(m.Trader)
		copy(dAtA[i:], m.Trader)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Trader)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CurrencyRate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrencyRate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrencyRate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdated != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.LastUpdated))
		i--
		dAtA[i] = 0x18
	}
	if m.RateToKes != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.RateToKes))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Currency) > 0 {
		i -= len(m.Currency)
		copy(dAtA[i:], m.Currency)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Currency)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMarket(dAtA []byte, offset int, v uint64) int {
	offset -= sovMarket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MarketPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BuyPrice != 0 {
		n += 1 + sovMarket(uint64(m.BuyPrice))
	}
	if m.SellPrice != 0 {
		n += 1 + sovMarket(uint64(m.SellPrice))
	}
	if m.TotalBuyVolume != 0 {
		n += 1 + sovMarket(uint64(m.TotalBuyVolume))
	}
	if m.TotalSellVolume != 0 {
		n += 1 + sovMarket(uint64(m.TotalSellVolume))
	}
	if m.LastUpdateHeight != 0 {
		n += 1 + sovMarket(uint64(m.LastUpdateHeight))
	}
	return n
}

func (m *KesBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	if m.Balance != 0 {
		n += 1 + sovMarket(uint64(m.Balance))
	}
	return n
}

func (m *Trade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	l = len(m.Trader)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	l = len(m.TradeType)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	if m.MlcnAmount != 0 {
		n += 1 + sovMarket(uint64(m.MlcnAmount))
	}
	if m.KesAmount != 0 {
		n += 1 + sovMarket(uint64(m.KesAmount))
	}
	if m.Price != 0 {
		n += 1 + sovMarket(uint64(m.Price))
	}
	if m.Timestamp != 0 {
		n += 1 + sovMarket(uint64(m.Timestamp))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovMarket(uint64(m.BlockHeight))
	}
	return n
}

func (m *CurrencyRate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Currency)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	if m.RateToKes != 0 {
		n += 1 + sovMarket(uint64(m.RateToKes))
	}
	if m.LastUpdated != 0 {
		n += 1 + sovMarket(uint64(m.LastUpdated))
	}
	return n
}

func sovMarket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMarket(x uint64) (n int) {
	return sovMarket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MarketPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarketPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarketPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyPrice", wireType)
			}
			m.BuyPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BuyPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellPrice", wireType)
			}
			m.SellPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SellPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBuyVolume", wireType)
			}
			m.TotalBuyVolume = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalBuyVolume |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSellVolume", wireType)
			}
			m.TotalSellVolume = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSellVolume |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdateHeight", wireType)
			}
			m.LastUpdateHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdateHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KesBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KesBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KesBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			m.Balance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Balance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Trade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Trade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Trade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trader", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Trader = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradeType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MlcnAmount", wireType)
			}
			m.MlcnAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MlcnAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KesAmount", wireType)
			}
			m.KesAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KesAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrencyRate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrencyRate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrencyRate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Currency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateToKes", wireType)
			}
			m.RateToKes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RateToKes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdated", wireType)
			}
			m.LastUpdated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdated |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMarket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMarket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMarket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMarket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMarket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMarket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMarket = fmt.Errorf("proto: unexpected end of group")
)
